import * as T from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {createConceptProduct} from './product-scene';
export function createDropGallery(container:HTMLElement,{count,worlds,reduced,onReady,onError,onSelect,onOpen}:{count:number;worlds?:number[];reduced:boolean;onReady:()=>void;onError:()=>void;onSelect:(i:number)=>void;onOpen:()=>void}){
 const renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.3:1.7));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;container.appendChild(renderer.domElement);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(32,1,.1,70);camera.position.set(0,.6,11);camera.lookAt(0,.1,0);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.035);scene.environment=environment.texture;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight('#fffaf5','#73314b',2.4));const key=new T.DirectionalLight('#ffffff',4);key.position.set(3,5,5);scene.add(key);const fill=new T.DirectionalLight('#ffe2ea',2.6);fill.position.set(-5,2,-2);scene.add(fill);
 const objects:T.Group[]=[];for(let i=0;i<count;i++){const slot=new T.Group();slot.add(createConceptProduct(worlds?.[i]??i%5));slot.userData.index=i;objects.push(slot);scene.add(slot)}
 const environments:T.Group[]=[];
 const tones=['#d38da7','#4ba9ed','#cd7699','#e5b15c','#b7a6e1'];
 const keyTones=['#fff1f5','#d9efff','#ffe1ec','#ffe1ae','#f0eaff'];
 for(let i=0;i<count;i++){
  const kind=worlds?.[i]??i%5;const room=new T.Group();const metal=new T.MeshStandardMaterial({color:tones[kind],metalness:.68,roughness:.26});const pearl=new T.MeshPhysicalMaterial({color:tones[kind],metalness:.18,roughness:.12,transmission:.4,thickness:.7,clearcoat:1});
  const add=(g:T.BufferGeometry,m:T.Material,x:number,y:number,z:number)=>{const o=new T.Mesh(g,m);o.position.set(x,y,z);room.add(o);return o};
  if(kind===0){for(let j=0;j<3;j++){const ring=add(new T.TorusGeometry(3.2+j*.55,.09,12,100),j===1?metal:pearl,0,-.2,-7-j*.8);ring.scale.set(1,1.18,1);ring.rotation.y=.18-j*.12;ring.rotation.z=.18}}
  else if(kind===1){for(let j=-3;j<=3;j++){const panel=add(new T.BoxGeometry(.11,8,2),j%2===0?metal:pearl,j*1.45,.4,-7-Math.abs(j)*.35);panel.rotation.y=-.35}add(new T.CylinderGeometry(7,7,.1,80),metal,0,-2.9,-8)}
  else if(kind===2){for(let j=0;j<4;j++){const arc=add(new T.TorusGeometry(2.4+j*.8,.16,16,100,Math.PI*1.5),j%2?metal:pearl,0,.4,-7-j*.4);arc.rotation.z=-Math.PI*.25}}
  else if(kind===3){for(let j=-2;j<=2;j++){add(new T.CylinderGeometry(.45,.45,6.5+Math.abs(j),48),metal,j*2.2,.3,-8);add(new T.CylinderGeometry(.6,.6,.16,48),pearl,j*2.2,3.55+Math.abs(j)*.5,-8)}add(new T.TorusGeometry(4,.055,10,100),metal,0,.8,-9)}
  else{for(let j=0;j<3;j++){const frame=add(new T.TorusGeometry(3.5-j*.55,.13,12,4),j===1?metal:pearl,0,.3,-8-j);frame.rotation.z=Math.PI/4;frame.rotation.y=.22}const orb=add(new T.SphereGeometry(1.1,48,32),pearl,-4.4,2.3,-8);orb.scale.set(1,1.2,1)}
  const mats=new Set<T.Material>();room.traverse(o=>{if(o instanceof T.Mesh)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{m.transparent=true;m.depthWrite=false;mats.add(m)})});room.userData.materials=[...mats];room.userData.alpha=i===0?1:0;environments.push(room);scene.add(room);
 }
 const accents=new T.Group();scene.add(accents);
 const floor=new T.Mesh(new T.CircleGeometry(8,96),new T.MeshPhysicalMaterial({color:'#fff7f4',roughness:.3,metalness:.25,transparent:true,opacity:.22,depthWrite:false}));floor.rotation.x=-Math.PI/2;floor.position.set(0,-2.55,-2);accents.add(floor);
 const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const context=canvas.getContext('2d');if(context){const gradient=context.createRadialGradient(64,64,2,64,64,64);gradient.addColorStop(0,'rgba(52,24,38,.3)');gradient.addColorStop(.45,'rgba(52,24,38,.1)');gradient.addColorStop(1,'rgba(52,24,38,0)');context.fillStyle=gradient;context.fillRect(0,0,128,128)}const shadowTexture=new T.CanvasTexture(canvas);const shadow=new T.Mesh(new T.PlaneGeometry(5,4),new T.MeshBasicMaterial({map:shadowTexture,transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.set(0,-2.52,0);accents.add(shadow);
 const beautyLight=new T.PointLight('#fff9f1',18,22,2);beautyLight.position.set(2.8,3.6,4);scene.add(beautyLight);const edgeLight=new T.PointLight('#edc5d5',12,22,2);edgeLight.position.set(-3,1,2);scene.add(edgeLight);
 const dustGeometry=new T.BufferGeometry(),dustPositions=new Float32Array((innerWidth<700?26:62)*3);for(let i=0;i<dustPositions.length;i+=3){dustPositions[i]=(Math.random()-.5)*16;dustPositions[i+1]=(Math.random()-.5)*10;dustPositions[i+2]=-2-Math.random()*8}dustGeometry.setAttribute('position',new T.BufferAttribute(dustPositions,3));const dustMaterial=new T.PointsMaterial({color:'#fff7eb',size:.026,transparent:true,opacity:.44,depthWrite:false,sizeAttenuation:true});const dust=new T.Points(dustGeometry,dustMaterial);dust.visible=!reduced;scene.add(dust);
 let disposed=false,visible=true,target=0,current=0,raf=0,previous=0,width=0,height=0,pointerX=0,pointerY=0,startX=0,startY=0,down=false;
 const resize=()=>{width=container.clientWidth;height=container.clientHeight;if(!width||!height)return;renderer.setSize(width,height);camera.aspect=width/height;camera.position.z=width<700?13.8:10.6;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(container);resize();const visibility=new IntersectionObserver(e=>{visible=e[0].isIntersecting});visibility.observe(container);
 const ray=new T.Raycaster(),pointer=new T.Vector2();const hit=(e:PointerEvent)=>{const r=container.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const intersections=ray.intersectObjects(objects,true);if(!intersections.length)return null;let object=intersections[0].object;while(object.parent&&object.userData.index===undefined)object=object.parent;return typeof object.userData.index==='number'?object.userData.index:null};
 const move=(e:PointerEvent)=>{const r=container.getBoundingClientRect();pointerX=((e.clientX-r.left)/r.width-.5)*2;pointerY=((e.clientY-r.top)/r.height-.5)*2;if(e.pointerType==='mouse')renderer.domElement.style.cursor=hit(e)!==null?'pointer':'default'};
 const press=(e:PointerEvent)=>{down=true;startX=e.clientX;startY=e.clientY};const release=(e:PointerEvent)=>{if(!down)return;down=false;const dx=e.clientX-startX,dy=e.clientY-startY;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)){onSelect(Math.max(0,Math.min(count-1,Math.round(target)+(dx<0?1:-1))));return}if(Math.hypot(dx,dy)>12)return;const index=hit(e);if(index!==null){if(index===Math.round(target))onOpen();else onSelect(index)}};
 const cancel=()=>{down=false;pointerX=0;pointerY=0};container.addEventListener('pointermove',move);container.addEventListener('pointerdown',press);container.addEventListener('pointerup',release);container.addEventListener('pointercancel',cancel);container.addEventListener('pointerleave',cancel);
 const lost=(e:Event)=>{e.preventDefault();cancelAnimationFrame(raf);onError()};renderer.domElement.addEventListener('webglcontextlost',lost);
 function disposeObject(object:T.Object3D){const geometry=new Set<T.BufferGeometry>(),material=new Set<T.Material>(),textures=new Set<T.Texture>();object.traverse(o=>{if(o instanceof T.Mesh){geometry.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){material.add(m);Object.values(m).forEach(v=>{if(v instanceof T.Texture)textures.add(v)})}}});textures.forEach(t=>t.dispose());geometry.forEach(g=>g.dispose());material.forEach(m=>m.dispose())}
 function layout(time:number){if(!reduced){dust.rotation.y=time*.000014;dust.position.y=Math.sin(time*.00013)*.18;beautyLight.position.x=2.8+Math.sin(time*.00025)*.8;edgeLight.position.x=-3+pointerX*.7;shadow.scale.setScalar(.93+Math.sin(time*.00065)*.025)}const world=worlds?.[Math.round(target)]??Math.round(target)%5;edgeLight.color.lerp(new T.Color(tones[world]),reduced?1:.05);fill.color.lerp(new T.Color(tones[world]),reduced?1:.05);key.color.lerp(new T.Color(keyTones[world]),reduced?1:.05);(floor.material as T.MeshPhysicalMaterial).color.lerp(new T.Color(keyTones[world]),reduced?1:.05);environments.forEach((room,i)=>{const destination=i===Math.round(target)?1:0;room.userData.alpha=reduced?destination:T.MathUtils.lerp(room.userData.alpha,destination,.065);room.visible=room.userData.alpha>.015;for(const m of room.userData.materials as T.Material[])m.opacity=room.userData.alpha*.22;if(room.visible&&!reduced)room.rotation.y=Math.sin(time*.00012)*.035});current=reduced?target:T.MathUtils.lerp(current,target,.075);objects.forEach((object,i)=>{let delta=i-current;if(delta>count/2)delta-=count;if(delta<-count/2)delta+=count;const angle=delta*.74;const central=Math.max(0,1-Math.abs(delta));object.position.set(Math.sin(angle)*(width<700?5.9:6.7),.08+(reduced?0:Math.sin(time*.00065+i)*.1),Math.cos(angle)*3.6-3.6);object.rotation.set(Math.sin(angle)*.06,Math.sin(angle)*.22+(reduced?0:pointerX*.08*central),-Math.sin(angle)*.23);object.scale.setScalar(.74+central*.3);object.visible=Math.abs(delta)<2.6&&!object.userData.failedAsset});camera.position.x=reduced?0:T.MathUtils.lerp(camera.position.x,pointerX*.12,.05);camera.position.y=reduced?.6:T.MathUtils.lerp(camera.position.y,.6-pointerY*.1,.05);camera.lookAt(0,.1,0)}
 function frame(time:number){if(disposed)return;raf=requestAnimationFrame(frame);if(!visible||document.hidden||time-previous<33)return;previous=time;layout(time);renderer.render(scene,camera)}layout(0);renderer.render(scene,camera);onReady();raf=requestAnimationFrame(frame);
 return{hideProduct(i:number){if(objects[i])objects[i].userData.failedAsset=true},select(i:number){target=Math.max(0,Math.min(count-1,i))},loadApproved(index:number,url:string){return new Promise<boolean>(resolve=>{let finished=false;const settle=(ok:boolean)=>{if(finished)return;finished=true;clearTimeout(timeout);resolve(ok)};const timeout=setTimeout(()=>settle(false),20000);new GLTFLoader().load(url,gltf=>{if(disposed||finished){disposeObject(gltf.scene);settle(false);return}const box=new T.Box3().setFromObject(gltf.scene),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3());const extent=Math.max(size.x,size.y,size.z);if(!Number.isFinite(extent)||extent<=0){disposeObject(gltf.scene);settle(false);return}const scale=3.8/extent;gltf.scene.scale.setScalar(scale);gltf.scene.position.copy(center.multiplyScalar(-scale));const slot=objects[index];slot.children.forEach(disposeObject);slot.clear();slot.add(gltf.scene);settle(true)},undefined,()=>settle(false))})},dispose(){disposed=true;cancelAnimationFrame(raf);observer.disconnect();visibility.disconnect();container.removeEventListener('pointermove',move);container.removeEventListener('pointerdown',press);container.removeEventListener('pointerup',release);container.removeEventListener('pointercancel',cancel);container.removeEventListener('pointerleave',cancel);renderer.domElement.removeEventListener('webglcontextlost',lost);objects.forEach(disposeObject);environments.forEach(disposeObject);disposeObject(accents);dustGeometry.dispose();dustMaterial.dispose();environment.dispose();renderer.dispose();renderer.domElement.remove()}};
}
