import * as T from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {createConceptProduct} from './product-scene';
export function createDropGallery(container:HTMLElement,{count,reduced,onReady,onError,onSelect,onOpen}:{count:number;reduced:boolean;onReady:()=>void;onError:()=>void;onSelect:(i:number)=>void;onOpen:()=>void}){
 const renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.3:1.7));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;container.appendChild(renderer.domElement);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(32,1,.1,70);camera.position.set(0,.6,11);camera.lookAt(0,.1,0);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.035);scene.environment=environment.texture;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight('#fffaf5','#73314b',2.4));const key=new T.DirectionalLight('#ffffff',4);key.position.set(3,5,5);scene.add(key);const fill=new T.DirectionalLight('#ffe2ea',2.6);fill.position.set(-5,2,-2);scene.add(fill);
 const objects:T.Group[]=[];for(let i=0;i<count;i++){const slot=new T.Group();slot.add(createConceptProduct(i));slot.userData.index=i;objects.push(slot);scene.add(slot)}
 let disposed=false,visible=true,target=0,current=0,raf=0,previous=0,width=0,height=0,pointerX=0,pointerY=0,startX=0,startY=0,down=false;
 const resize=()=>{width=container.clientWidth;height=container.clientHeight;if(!width||!height)return;renderer.setSize(width,height);camera.aspect=width/height;camera.position.z=width<700?13.8:10.6;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(container);resize();const visibility=new IntersectionObserver(e=>{visible=e[0].isIntersecting});visibility.observe(container);
 const ray=new T.Raycaster(),pointer=new T.Vector2();const hit=(e:PointerEvent)=>{const r=container.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const intersections=ray.intersectObjects(objects,true);if(!intersections.length)return null;let object=intersections[0].object;while(object.parent&&object.userData.index===undefined)object=object.parent;return typeof object.userData.index==='number'?object.userData.index:null};
 const move=(e:PointerEvent)=>{const r=container.getBoundingClientRect();pointerX=((e.clientX-r.left)/r.width-.5)*2;pointerY=((e.clientY-r.top)/r.height-.5)*2;if(e.pointerType==='mouse')renderer.domElement.style.cursor=hit(e)!==null?'pointer':'default'};
 const press=(e:PointerEvent)=>{down=true;startX=e.clientX;startY=e.clientY};const release=(e:PointerEvent)=>{if(!down)return;down=false;const dx=e.clientX-startX,dy=e.clientY-startY;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)){onSelect(Math.max(0,Math.min(count-1,Math.round(target)+(dx<0?1:-1))));return}if(Math.hypot(dx,dy)>12)return;const index=hit(e);if(index!==null){if(index===Math.round(target))onOpen();else onSelect(index)}};
 const cancel=()=>{down=false;pointerX=0;pointerY=0};container.addEventListener('pointermove',move);container.addEventListener('pointerdown',press);container.addEventListener('pointerup',release);container.addEventListener('pointercancel',cancel);container.addEventListener('pointerleave',cancel);
 const lost=(e:Event)=>{e.preventDefault();cancelAnimationFrame(raf);onError()};renderer.domElement.addEventListener('webglcontextlost',lost);
 function disposeObject(object:T.Object3D){const geometry=new Set<T.BufferGeometry>(),material=new Set<T.Material>(),textures=new Set<T.Texture>();object.traverse(o=>{if(o instanceof T.Mesh){geometry.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){material.add(m);Object.values(m).forEach(v=>{if(v instanceof T.Texture)textures.add(v)})}}});textures.forEach(t=>t.dispose());geometry.forEach(g=>g.dispose());material.forEach(m=>m.dispose())}
 function layout(time:number){current=reduced?target:T.MathUtils.lerp(current,target,.075);objects.forEach((object,i)=>{let delta=i-current;if(delta>count/2)delta-=count;if(delta<-count/2)delta+=count;const angle=delta*.74;const central=Math.max(0,1-Math.abs(delta));object.position.set(Math.sin(angle)*(width<700?5.9:6.7),.08+(reduced?0:Math.sin(time*.00065+i)*.1),Math.cos(angle)*3.6-3.6);object.rotation.set(Math.sin(angle)*.06,Math.sin(angle)*.22+(reduced?0:pointerX*.08*central),-Math.sin(angle)*.23);object.scale.setScalar(.74+central*.3);object.visible=Math.abs(delta)<2.6});camera.position.x=reduced?0:T.MathUtils.lerp(camera.position.x,pointerX*.12,.05);camera.position.y=reduced?.6:T.MathUtils.lerp(camera.position.y,.6-pointerY*.1,.05);camera.lookAt(0,.1,0)}
 function frame(time:number){if(disposed)return;raf=requestAnimationFrame(frame);if(!visible||document.hidden||time-previous<33)return;previous=time;layout(time);renderer.render(scene,camera)}layout(0);renderer.render(scene,camera);onReady();raf=requestAnimationFrame(frame);
 return{select(i:number){target=Math.max(0,Math.min(count-1,i))},async loadApproved(index:number,url:string){new GLTFLoader().load(url,gltf=>{if(disposed){disposeObject(gltf.scene);return}const box=new T.Box3().setFromObject(gltf.scene),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3());const scale=3.8/Math.max(size.x,size.y,size.z);gltf.scene.scale.setScalar(scale);gltf.scene.position.copy(center.multiplyScalar(-scale));const slot=objects[index];slot.children.forEach(disposeObject);slot.clear();slot.add(gltf.scene)},undefined,()=>{/* Keep the labeled concept on a failed approved asset load. */})},dispose(){disposed=true;cancelAnimationFrame(raf);observer.disconnect();visibility.disconnect();container.removeEventListener('pointermove',move);container.removeEventListener('pointerdown',press);container.removeEventListener('pointerup',release);container.removeEventListener('pointercancel',cancel);container.removeEventListener('pointerleave',cancel);renderer.domElement.removeEventListener('webglcontextlost',lost);objects.forEach(disposeObject);environment.dispose();renderer.dispose();renderer.domElement.remove()}};
}
