import * as T from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
export function createProductScene(container:HTMLElement,{index=0,url,onReady,onError}:{index?:number;url?:string;onReady:()=>void;onError:()=>void}){
 const renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;container.appendChild(renderer.domElement);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(32,1,.1,100);camera.position.set(5,3.4,9);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();const environment=pmrem.fromScene(room,.03);scene.environment=environment.texture;room.dispose();pmrem.dispose();
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.35,0);controls.enablePan=false;controls.enableZoom=false;controls.minPolarAngle=.6;controls.maxPolarAngle=1.7;controls.enableDamping=true;controls.autoRotate=!matchMedia('(prefers-reduced-motion: reduce)').matches;controls.autoRotateSpeed=.5;
 scene.add(new T.HemisphereLight('#ffffff','#392331',2));const key=new T.DirectionalLight('#fff9f0',5);key.position.set(3,7,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);const rim=new T.DirectionalLight('#d9e9ff',3);rim.position.set(-4,3,-4);scene.add(rim);
 const group=url?new T.Group():createConceptProduct(index);scene.add(group);
 const pedestal=new T.Mesh(new T.CylinderGeometry(1.35,1.4,.35,96),new T.MeshStandardMaterial({color:'#542239',roughness:.25,metalness:.18}));pedestal.position.y=-1.82;pedestal.receiveShadow=true;scene.add(pedestal);
 const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.17}));floor.rotation.x=-Math.PI/2;floor.position.y=-2;floor.receiveShadow=true;scene.add(floor);
 let disposed=false,raf=0,visible=true,loaded:T.Object3D|undefined;
 function free(object:T.Object3D){object.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>{Object.values(m).forEach(v=>{if(v instanceof T.Texture)v.dispose()});m.dispose()})}})}
 if(url)new GLTFLoader().load(url,gltf=>{if(disposed){free(gltf.scene);return}loaded=gltf.scene;const box=new T.Box3().setFromObject(loaded),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3());const scale=3.7/Math.max(size.x,size.y,size.z);loaded.scale.setScalar(scale);loaded.position.copy(center.multiplyScalar(-scale));loaded.position.y+=.15;loaded.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true}});group.add(loaded);onReady()},undefined,onError);else onReady();
 const resize=()=>{const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.position.z=w/h<.8?13:9;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(container);resize();const intersection=new IntersectionObserver(e=>{visible=e[0].isIntersecting});intersection.observe(container);
 const loss=(e:Event)=>{e.preventDefault();onError();cancelAnimationFrame(raf)};renderer.domElement.addEventListener('webglcontextlost',loss);
 let previous=0;function animate(time:number){if(disposed)return;raf=requestAnimationFrame(animate);if(!visible||document.hidden||time-previous<30)return;previous=time;controls.update();renderer.render(scene,camera)}raf=requestAnimationFrame(animate);
 return{reset(){camera.position.set(5,3.4,container.clientWidth/container.clientHeight<.8?13:9);controls.target.set(0,.35,0);controls.update()},dispose(){disposed=true;cancelAnimationFrame(raf);observer.disconnect();intersection.disconnect();controls.dispose();free(scene);environment.dispose();renderer.dispose();renderer.domElement.remove()}};
}
export function createConceptProduct(index=0){
 const group=new T.Group();const palette=['#de9caf','#97bccb','#b76480','#b79764','#bfaeb7'];const chrome=new T.MeshStandardMaterial({color:'#f4ecea',metalness:1,roughness:.14});const glass=new T.MeshPhysicalMaterial({color:palette[index%5],roughness:.13,metalness:.04,transmission:.75,thickness:.9,ior:1.48,clearcoat:1});const opaque=new T.MeshPhysicalMaterial({color:palette[index%5],roughness:.24,metalness:.12,clearcoat:1});
 function add(geometry:T.BufferGeometry,material:T.Material,x=0,y=0,z=0){const m=new T.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;group.add(m);return m;}
 function lathe(points:number[][],mat:T.Material){return add(new T.LatheGeometry(points.map(([x,y])=>new T.Vector2(x,y)),96),mat)}
 {
  if(index===1){const shape=new T.Shape();const w=.75,h=1.1,r=.18;shape.moveTo(-w+r,-h);shape.lineTo(w-r,-h);shape.quadraticCurveTo(w,-h,w,-h+r);shape.lineTo(w,h-r);shape.quadraticCurveTo(w,h,w-r,h);shape.lineTo(-w+r,h);shape.quadraticCurveTo(-w,h,-w,h-r);shape.lineTo(-w,-h+r);shape.quadraticCurveTo(-w,-h,-w+r,-h);const body=add(new T.ExtrudeGeometry(shape,{depth:.8,bevelEnabled:true,bevelSegments:8,steps:1,bevelSize:.08,bevelThickness:.08}),opaque,0,-.2,-.4);add(new T.CylinderGeometry(.44,.44,.58,96),chrome,0,1.2);body.rotation.y=0;}
  else if(index===2){lathe([[0,-1.2],[.85,-1.2],[.95,-1.1],[.95,-.4],[.92,-.3],[0,-.3]],glass);add(new T.CylinderGeometry(.98,.98,.33,96),chrome,0,-.12);}
  else{lathe([[0,-1.6],[.48,-1.6],[.65,-1.5],[.67,-1.28],[.67,.65],[.64,.82],[.47,1.02],[.26,1.12],[.26,1.35],[0,1.35]],glass);add(new T.CylinderGeometry(.54,.54,2.08,80),opaque,0,-.37);add(new T.CylinderGeometry(.33,.33,.65,96),chrome,0,1.52);if(index===0){lathe([[0,1.83],[.21,1.83],[.24,1.91],[.24,2.18],[.17,2.32],[0,2.36]],new T.MeshStandardMaterial({color:'#3d1d29',roughness:.48}));}else add(new T.CylinderGeometry(.34,.34,.18,96),chrome,0,1.95);for(let j=0;j<18;j++){const groove=add(new T.TorusGeometry(.333,.006,5,80),chrome,0,1.26+j*.029);groove.rotation.x=Math.PI/2;}}
  const canvas=document.createElement('canvas');canvas.width=768;canvas.height=1024;const ctx=canvas.getContext('2d')!;ctx.clearRect(0,0,768,1024);ctx.fillStyle='#361b27';ctx.textAlign='center';ctx.font='42px Georgia';ctx.fillText('ATELIER',384,200);ctx.font='150px Georgia';ctx.fillText('0'+(index+1),384,370);ctx.font='23px Arial';ctx.fillText(['PETAL RESET','BLUE HOUR','SOFT FOCUS','GOLDEN RITUAL','FIRST LIGHT'][index%5],384,540);ctx.font='18px Arial';ctx.fillText('EDITORIAL CONCEPT',384,610);ctx.fillText('30 ML / 1 FL OZ',384,790);const map=new T.CanvasTexture(canvas);map.colorSpace=T.SRGBColorSpace;add(new T.PlaneGeometry(index===1?1.2:1.02,index===2?.6:1.9),new T.MeshBasicMaterial({map,transparent:true,depthWrite:false}),0,index===2?-.65:-.28,index===1?.52:index===2?.951:.672);
  if(index===2)group.position.y=.65;
 }

const used=new Set<T.Material>();group.traverse(o=>{if(o instanceof T.Mesh)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>used.add(m))});for(const m of [chrome,glass,opaque])if(!used.has(m))m.dispose();return group;
}
