import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {createHash,randomUUID,webcrypto} from 'node:crypto';
function moduleAt(path,dependencies={}){const exports={};const js=ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(js,{exports,require:n=>{if(!(n in dependencies))throw Error('Unexpected dependency '+n);return dependencies[n]},crypto:webcrypto,URL,Date,console});return exports}
const {verifiedReceipts}=moduleAt('../lib/settlement-contract.ts');
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));function statement(q,...args){return {run:async()=>sql.prepare(q).run(...args),first:async()=>sql.prepare(q).get(...args)||null,all:async()=>({results:sql.prepare(q).all(...args)}),sql:q,args}}const database=()=>({prepare:q=>({bind:(...args)=>statement(q,...args)}),batch:async statements=>{sql.exec('BEGIN');try{for(const s of statements)sql.prepare(s.sql).run(...s.args);sql.exec('COMMIT')}catch(e){sql.exec('ROLLBACK');throw e}}});const one=async(q,...args)=>sql.prepare(q).get(...args)||null,rows=async(q,...args)=>sql.prepare(q).all(...args),iso=()=>new Date().toISOString(),digest=async value=>createHash('sha256').update(value).digest('hex');let response=[],invoice=0;const types=moduleAt('../lib/commerce-types.ts');const store=moduleAt('../lib/commerce-store.ts',{'@/db/raw':{database},'./catalog':moduleAt('../lib/catalog.ts'),'./runtime-config':{configuration:()=>({})},'./commerce-types':types});const service=moduleAt('../lib/checkout-service.ts',{'@/db/raw':{database},'./commerce-types':types,'./commerce-store':store,'./runtime-config':{configuration:()=>({APP_URL:'https://example.test'})},'./commerce-payments':{paymentReady:()=>true,digest,issueInvoice:async()=>({invoice_id:'invoice-'+(++invoice),qr_image:'fixture',urls:[]}),providerPayments:async()=>response,cancelInvoice:async()=>{}},'./settlement-contract':{verifiedReceipts}});
 const opens=new Date(Date.now()-60000).toISOString(),closes=new Date(Date.now()+3600000).toISOString();sql.prepare('INSERT INTO campaigns(id,name,brand,status,opens_at,closes_at,approved_by,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run('drop','Test','TEST BRAND','LIVE',opens,closes,'reviewer','admin',iso());sql.prepare('INSERT INTO commerce_content(campaign_id,content,review_by) VALUES(?,?,?)').run('drop','{}','reviewer');sql.prepare('INSERT INTO commerce_variants(id,campaign_id,sku,label,price_mnt,map_mnt,allocation,moq,max_per_customer) VALUES(?,?,?,?,?,?,?,?,?)').run('variant','drop','SKU','50 ml',100000,90000,2,1,2);
 const user={userId:'customer',email:'customer@example.test'},input=()=>({idempotencyKey:randomUUID(),acceptedTerms:true,items:[{drop_id:'drop',variant:'50 ml',quantity:1}],address:{name:'Customer',phone:'99112233',city:'UB',district:'Sukhbaatar',street:'Test address'}}),receipt=(order,overrides={})=>({payment_id:'payment-'+order.id,payment_status:'PAID',payment_currency:'MNT',payment_amount:'100000',object_type:'INVOICE',object_id:order.invoice_id,...overrides});return {sql,service,store,user,input,digest,receipt,setResponse:r=>response=r,one}}
test('concurrent reservations cannot oversell and rollback leaves no orphan orders',async()=>{const f=fixture();const results=await Promise.allSettled([1,2,3].map(()=>f.service.reserveCheckout(f.input(),f.user)));assert.equal(results.filter(x=>x.status==='fulfilled').length,2);assert.equal((await f.one('SELECT COUNT(*) n FROM orders')).n,2);assert.equal((await f.one('SELECT reserved FROM commerce_variants')).reserved,2);assert.equal((await f.one('SELECT quantity FROM commerce_usage')).quantity,2)});
test('checkout retry returns the same order without a second invoice or reservation',async()=>{const f=fixture(),input=f.input(),a=await f.service.reserveCheckout(input,f.user),b=await f.service.reserveCheckout(input,f.user);assert.equal(a.id,b.id);assert.equal((await f.one('SELECT reserved FROM commerce_variants')).reserved,1)});
test('closed campaign is blocked even when cached cart and future dates exist',async()=>{const f=fixture();f.sql.exec("UPDATE campaigns SET status='CLOSED'");await assert.rejects(()=>f.service.reserveCheckout(f.input(),f.user));assert.equal((await f.one('SELECT COUNT(*) n FROM orders')).n,0)});
test('verified settlement is idempotent and consumes allocation exactly once',async()=>{const f=fixture(),o=await f.service.reserveCheckout(f.input(),f.user);const secret='callback-secret';f.sql.prepare('UPDATE commerce_order_meta SET callback_hash=?').run(await f.digest(secret));f.setResponse([f.receipt(o)]);await Promise.allSettled([f.service.receivePayment(o.id,secret),f.service.receivePayment(o.id,secret)]);assert.equal((await f.one('SELECT status FROM orders')).status,'PAID');assert.deepEqual({...await f.one('SELECT reserved,paid_qty FROM commerce_variants')},{reserved:0,paid_qty:1});assert.equal((await f.one('SELECT COUNT(*) n FROM commerce_receipts')).n,1)});
test('forged callback, wrong currency, wrong invoice and amount never mark paid',async()=>{const f=fixture(),o=await f.service.reserveCheckout(f.input(),f.user),secret='callback-secret';f.sql.prepare('UPDATE commerce_order_meta SET callback_hash=?').run(await f.digest(secret));await assert.rejects(()=>f.service.receivePayment(o.id,'forged'));for(const bad of [{payment_currency:'USD'},{object_id:'another-invoice'},{payment_amount:'99999'}]){f.setResponse([f.receipt(o,bad)]);await assert.rejects(()=>f.service.receivePayment(o.id,secret))}assert.equal((await f.one('SELECT status FROM orders')).status,'PAYMENT_PENDING');assert.equal((await f.one('SELECT paid_qty FROM commerce_variants')).paid_qty,0)});
test('late verified payment after provider cancellation requires refund without consuming stock',async()=>{const f=fixture(),o=await f.service.reserveCheckout(f.input(),f.user),secret='callback-secret';f.sql.prepare('UPDATE commerce_order_meta SET callback_hash=?,expires_at=?').run(await f.digest(secret),new Date(Date.now()-1000).toISOString());await f.service.expireInvoice(o.id);f.setResponse([f.receipt(o)]);await f.service.receivePayment(o.id,secret);assert.equal((await f.one('SELECT status FROM orders')).status,'REFUND_REQUIRED');assert.deepEqual({...await f.one('SELECT reserved,paid_qty FROM commerce_variants')},{reserved:0,paid_qty:0});assert.equal((await f.one('SELECT quantity FROM commerce_usage')).quantity,0)});

test('exact paid-only consolidation prepares one immutable PO and blocks unmet MOQ',async()=>{const f=fixture(),order=await f.service.reserveCheckout(f.input(),f.user),secret='callback-secret';f.sql.prepare('UPDATE commerce_order_meta SET callback_hash=?').run(await f.digest(secret));f.setResponse([f.receipt(order)]);await f.service.receivePayment(order.id,secret);f.sql.exec("UPDATE campaigns SET status='CLOSED';UPDATE commerce_variants SET moq=2");await assert.rejects(()=>f.store.preparePo('drop','reviewer'));assert.equal((await f.one('SELECT COUNT(*) n FROM commerce_purchase_orders')).n,0);f.sql.exec('UPDATE commerce_variants SET moq=1');const po=await f.store.preparePo('drop','reviewer');assert.equal(po.quantities[0].quantity,1);const repeat=await f.store.preparePo('drop','reviewer');assert.equal(po.id,repeat.id);assert.equal((await f.one('SELECT COUNT(*) n FROM commerce_purchase_orders')).n,1)});
test('consolidation blocks unresolved invoices instead of inflating paid quantities',async()=>{const f=fixture();await f.service.reserveCheckout(f.input(),f.user);f.sql.exec("UPDATE campaigns SET status='CLOSED'");await assert.rejects(()=>f.store.preparePo('drop','reviewer'));assert.equal((await f.one('SELECT COUNT(*) n FROM commerce_purchase_orders')).n,0)});
test('publication requires brand evidence, complete bilingual content and approved model',async()=>{const f=fixture();f.sql.exec("UPDATE campaigns SET status='DRAFT',approved_by=NULL;DELETE FROM commerce_content");const content={environment:0,authorizationId:'authorization',image:'https://example.test/approved.jpg',modelId:'approved-model',variants:[{sku:'SKU',label:'50 ml',priceMnt:100000,mapMnt:90000,allocation:10,moq:1,maxPerCustomer:2}]};for(const k of ['titleMn','descriptionEn','descriptionMn','category','refundEn','refundMn','deliveryEn','deliveryMn','sourcingEn','sourcingMn','ingredientsEn','ingredientsMn','usageEn','usageMn'])content[k]='Reviewed '+k;await f.store.saveContent('drop',content,'reviewer');await assert.rejects(()=>f.store.changeCampaign('drop','UPCOMING','reviewer'));await assert.rejects(()=>f.store.reviewCampaign('drop','reviewer',true));f.sql.prepare('INSERT INTO authorizations(id,brand,document_url,valid_until,created_by) VALUES(?,?,?,?,?)').run('authorization','TEST BRAND','https://example.test/evidence','2030-01-01T00:00:00.000Z','admin');await assert.rejects(()=>f.store.reviewCampaign('drop','reviewer',true));f.sql.prepare('INSERT INTO model_jobs(id,name,created_by,created_at,status,source_kind) VALUES(?,?,?,?,?,?)').run('approved-model','Test','admin',new Date().toISOString(),'APPROVED','UPLOAD');await f.store.reviewCampaign('drop','reviewer',true);await f.store.changeCampaign('drop','UPCOMING','reviewer');await f.store.changeCampaign('drop','LIVE','reviewer');const catalog=await f.store.catalog();assert.equal(catalog[0].approved,true);assert.equal(catalog[0].variantRecords[0].remaining,10);await f.store.changeCampaign('drop','CLOSED','reviewer');await assert.rejects(()=>f.store.changeCampaign('drop','LIVE','reviewer'));assert.equal((await f.one('SELECT status FROM campaigns')).status,'CLOSED')});
