import test from 'node:test';
import assert from 'node:assert/strict';
import ts from 'typescript';
import {readFileSync} from 'node:fs';
function module(file,replacements){let source=readFileSync(new URL(file,import.meta.url),'utf8');for(const [from,to] of replacements)source=source.replace(from,to);return import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText).toString('base64'))}
const errors='class CommerceError extends Error {constructor(message,status=409){super(message);this.status=status}};';
const {sourceUrl,parseProduct}=await module('../lib/brand-web-import.ts',[["import {directoryBrands} from './brand-directory';",'const directoryBrands=[];'],["import {CommerceError} from './commerce-types';",errors]]);
const {validateProfile}=await module('../lib/customer-profile.ts',[["import {CommerceError,textValue} from './commerce-types';",errors+"function textValue(v,max){if(typeof v!=='string'||v.length>max)throw new CommerceError('Invalid text',400);return v.trim()}"]]);
test('website imports reject untrusted destinations and credentials',()=>{for(const url of ['http://brand.com/p','https://127.0.0.1/p','https://brand.com.evil.test/p','https://user:pass@brand.com/p','https://brand.com:8443/p'])assert.throws(()=>sourceUrl(url,'brand.com'));assert.equal(sourceUrl('https://www.brand.com/p#secret','brand.com').href,'https://www.brand.com/p')});
test('source currency and approval boundaries survive extraction',()=>{const p=parseProduct('<script type="application/ld+json">'+JSON.stringify({'@graph':[{'@type':'Product',name:'Serum',description:'<b>Hydration</b>',image:'/serum.jpg',offers:{price:'24.00',priceCurrency:'USD'}}]})+'</script>','https://brand.com/products/serum');assert.equal(p.offers[0].currency,'USD');assert.equal(p.offers[0].price,'24.00');assert.equal(p.images[0],'https://brand.com/serum.jpg');assert.equal(p.description,'Hydration');assert.equal(p.publicationApproved,false);assert.equal(p.mediaRightsApproved,false);assert.throws(()=>parseProduct('<html>No product</html>','https://brand.com/'))});
const contact={name:'Buyer',phone:'+976 9911-2233',city:'Улаанбаатар',district:'Хан-Уул',khoroo:'1',street:'Apartment 1',preferredContact:'email',privacyConsent:true};
test('profile requires consent and complete Mongolian contact details',()=>{assert.equal(validateProfile(contact).phone,'+97699112233');assert.equal(validateProfile(contact).marketingConsent,false);assert.throws(()=>validateProfile({...contact,privacyConsent:false}));assert.throws(()=>validateProfile({...contact,phone:'123'}));assert.throws(()=>validateProfile({...contact,street:''}));assert.throws(()=>validateProfile({...contact,deliveryNotes:'a'.repeat(501)}))});
