import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database,isAdmin,validOrigin} from '@/db/raw';
import {modelConfig,putModelFile} from '@/lib/model-storage';
import {MAX_IMAGE_BYTES,MAX_GLB_BYTES,imageMime,validateGlb,meshyPayload} from '@/lib/model-validation';
export async function GET(){const u=await getChatGPTUser();if(!u||!isAdmin(u.email))return Response.json({configured:false,jobs:[]},{status:403});try{const c=modelConfig();const jobs=await database().prepare('SELECT * FROM model_jobs WHERE created_by=? ORDER BY created_at DESC LIMIT 30').bind(u.userId).all();return Response.json({configured:!!c.key&&!!c.bucket,storage:!!c.bucket,jobs:jobs.results})}catch{return Response.json({error:'Model studio storage unavailable'},{status:503})}}
export async function POST(req:Request){if(!validOrigin(req))return Response.json({error:'Invalid origin'},{status:403});const u=await getChatGPTUser();if(!u||!isAdmin(u.email))return Response.json({error:'Administrative access required'},{status:403});const config=modelConfig();if(!config.bucket)return Response.json({error:'Media storage is not configured'},{status:503});if(Number(req.headers.get('content-length')||0)>MAX_GLB_BYTES+100000)return Response.json({error:'Upload is too large'},{status:413});
 let id:string|undefined;
 try{const data=await req.formData(),name=String(data.get('name')||'').trim(),mode=data.get('mode');if(!name||name.length>120)return Response.json({error:'Product name is required (120 characters maximum)'},{status:400});const files=data.getAll('files').filter((f):f is File=>f instanceof File);if(mode!=='glb'&&!config.key)return Response.json({error:'MESHY_API_KEY is not configured. You can still upload an existing GLB.'},{status:503});if(mode!=='glb'&&data.get('consent')!=='yes')return Response.json({error:'Confirm image rights and sending the images to Meshy'},{status:400});if(files.length<1||files.length>(mode==='glb'?1:4))return Response.json({error:'Upload one GLB or 1–4 product photographs'},{status:400});const validated: {bytes:Uint8Array;type:string}[]=[];for(const f of files){if(!f.size||f.size>(mode==='glb'?MAX_GLB_BYTES:MAX_IMAGE_BYTES))return Response.json({error:'Each photo must be under 5 MB; GLB under 40 MB'},{status:413});const bytes=new Uint8Array(await f.arrayBuffer());validated.push({bytes,type:mode==='glb'?(validateGlb(bytes),'model/gltf-binary'):imageMime(bytes)})}
 const db=database();const recent=await db.prepare('SELECT COUNT(*) AS n FROM model_jobs WHERE created_by=? AND created_at>?').bind(u.userId,new Date(Date.now()-86400000).toISOString()).first<any>();if(Number(recent?.n)>=10)return Response.json({error:'Daily studio limit reached (10 tasks)'},{status:429});id=crypto.randomUUID();const now=new Date().toISOString();await db.prepare('INSERT INTO model_jobs(id,name,created_by,created_at,status,progress,source_kind) VALUES(?,?,?,?,?,?,?)').bind(id,name,u.userId,now,'SUBMITTING',0,mode==='glb'?'UPLOAD':'MESHY').run();
 if(mode==='glb'){await putModelFile('models/'+id+'.glb',validated[0].bytes,'model/gltf-binary');await db.prepare('UPDATE model_jobs SET status=?,progress=?,asset_key=? WHERE id=?').bind('REVIEW',100,'models/'+id+'.glb',id).run()}
 else{const images:string[]=[];for(let i=0;i<validated.length;i++){const {bytes,type}=validated[i];await putModelFile('sources/'+id+'/'+i,bytes,type);let binary='';for(let j=0;j<bytes.length;j+=8192)binary+=String.fromCharCode(...bytes.subarray(j,j+8192));images.push('data:'+type+';base64,'+btoa(binary))}const response=await fetch('https://api.meshy.ai/openapi/v1/multi-image-to-3d',{method:'POST',headers:{Authorization:'Bearer '+config.key,'Content-Type':'application/json'},body:JSON.stringify(meshyPayload(images)),signal:AbortSignal.timeout(45000)});if(!response.ok)throw Error('3D provider rejected the request');const task:any=await response.json();if(typeof task.result!=='string'||!/^[a-zA-Z0-9-]{8,80}$/.test(task.result))throw Error('Invalid provider task');await db.prepare('UPDATE model_jobs SET status=?,provider_id=? WHERE id=?').bind('PENDING',task.result,id).run()}
 await db.prepare('INSERT INTO audit_logs(id,actor,action,record_id,detail,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.email,'model.create',id,JSON.stringify({mode,name}),now).run();return Response.json({id},{status:201});
 }catch(e){if(id)try{await database().prepare('UPDATE model_jobs SET status=?,error=? WHERE id=?').bind('FAILED','Submission failed. Check provider dashboard before submitting again.',id).run()}catch{}console.error('Model submission failed',e instanceof Error?e.message:'unknown');return Response.json({error:id?'Submission failed. Check Meshy dashboard before retrying to avoid a duplicate billed task.':(e instanceof Error?e.message:'Invalid upload')},{status:id?502:400})}}
