'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ChevronLeft,ChevronRight,ArrowDown} from 'lucide-react';
import {drops,effectiveStatus} from '@/lib/catalog';
import Countdown from './drop-countdown';
import ProductViewer from './product-viewer';
export default function BeautyWorld({mn}:{mn:boolean}){
 const [index,setIndex]=useState(0);const d=drops[index],status=effectiveStatus(d);const t=(a:string,b:string)=>mn?a:b;
 return <section className="drop-universe"><div className="universe-heading"><p className="eyebrow">THE BEAUTY DROP / VOLUME 01</p><h1>{t('Дараагийн','Your next')}<br/><em>{t('онцгой мөч.','obsession.')}</em></h1><p className="universe-intro">{t('Хязгаарлагдмал нээлт. Шинэ мэдрэмж.\nГоо сайхныг бүх өнцгөөс.','Limited releases. Uncommon beauty.\nA new perspective on your ritual.')}</p><Link className="text-link" href="/drops">{t('Дропуудыг нээх','Explore the drops')}<ArrowUpRight size={17}/></Link><span className="universe-coordinate">47.9185° N · 106.9177° E<br/>ULAANBAATAR, MONGOLIA</span></div><div className="universe-stage"><span className="giant-edition">0{index+1}</span><ProductViewer index={index} image={d.image} dropId={d.id}/><div className="universe-switch"><button aria-label="Previous drop" onClick={()=>setIndex((index+drops.length-1)%drops.length)}><ChevronLeft size={18}/></button><span>0{index+1} / 0{drops.length}</span><button aria-label="Next drop" onClick={()=>setIndex((index+1)%drops.length)}><ChevronRight size={18}/></button></div></div><div className="universe-drop"><div className="universe-drop-title"><p className="eyebrow">{d.brand} / {d.category}</p><h2>{mn?d.mn:d.name}</h2><span className="concept-pill">{t('КОНЦЕПЦ ЦУГЛУУЛГА','EDITORIAL CONCEPT')}</span></div><div className="universe-clock"><p>{status==='UPCOMING'?t('НЭЭГДЭХЭД','OPENS IN'):t('ДУУСАХАД','CLOSES IN')} <span>UTC +08:00</span></p><Countdown target={status==='UPCOMING'?d.opensAt:d.closesAt} mn={mn} closed={['CLOSED','ARCHIVED'].includes(status)}/></div><Link className="button black" href={'/drops/'+d.id}>{t('Дроп үзэх','Discover drop')}<ArrowUpRight size={18}/></Link></div><div className="universe-foot"><span>{t('ЗӨВХӨН ДРОП. ЗӨВХӨН ОНЦГОЙ.','DROP ONLY. ALWAYS EXCEPTIONAL.')}</span><a href="#next-drops">{t('ДАРААГИЙН НЭЭЛТҮҮД','THE NEXT RELEASES')}<ArrowDown size={14}/></a><Link href="/studio">IMAGE → 3D STUDIO<ArrowUpRight size={14}/></Link></div></section>
}
