'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {motion} from 'motion/react';
import {ArrowDown,ChevronLeft,ChevronRight,Plus,MoveUpRight} from 'lucide-react';
import {drops} from '@/lib/catalog';
export default function BeautyWorld({mn}:{mn:boolean}){
 const section=useRef<HTMLElement>(null),canvas=useRef<HTMLDivElement>(null),engine=useRef<ReturnType<typeof import('@/lib/three/beauty-scene').createBeautyScene>|null>(null),progress=useRef(0);
 const [index,setIndex]=useState(0),[ready,setReady]=useState(false),[fallback,setFallback]=useState(false),[reduced,setReduced]=useState(false);
 const manualRef=useRef<number|null>(null);const selected=drops[index];const t=(a:string,b:string)=>mn?a:b;
 useEffect(()=>{let cancelled=false;const media=matchMedia('(prefers-reduced-motion: reduce)');setReduced(media.matches);const container=canvas.current;if(!container)return;const update=()=>{if(!section.current)return;const rect=section.current.getBoundingClientRect();const range=Math.max(1,section.current.offsetHeight-window.innerHeight);const p=Math.max(0,Math.min(1,-rect.top/range));progress.current=p;if(manualRef.current!==null)return;engine.current?.setProgress(p);setIndex(Math.min(drops.length-1,Math.round(p*(drops.length-1))));};
  const wheel=()=>{manualRef.current=null;update()};window.addEventListener('scroll',wheel,{passive:true});window.addEventListener('resize',update);update();
  import('@/lib/three/beauty-scene').then(module=>{if(cancelled)return;try{engine.current=module.createBeautyScene({container,count:drops.length,reducedMotion:media.matches,onReady:()=>setReady(true),onError:()=>{setFallback(true);setReady(false)}});engine.current.setProgress(progress.current);}catch{setFallback(true);}}).catch(()=>{if(!cancelled)setFallback(true)});
  const change=()=>{setReduced(media.matches);setFallback(true);engine.current?.dispose();engine.current=null;};media.addEventListener('change',change);
  return()=>{cancelled=true;engine.current?.dispose();engine.current=null;window.removeEventListener('scroll',wheel);window.removeEventListener('resize',update);media.removeEventListener('change',change)};
 },[]);
 function select(next:number){const i=Math.max(0,Math.min(drops.length-1,next));manualRef.current=i;setIndex(i);engine.current?.setProgress(i/(drops.length-1));}
 return <section className={'beauty-world '+(ready?'is-ready ':'')+(fallback?'is-fallback ':'')+(reduced?'reduced-motion':'')} ref={section} aria-label={t('3D дропын цуглуулга','3D drop collection')}><div className="world-sticky"><div className="world-backdrop"><span className="world-kicker">BEAUTY, IN ITS OWN TIME.</span><h1>Rare beauty.<br/><em>Real moments.</em></h1><span className="world-location">ULAANBAATAR • UTC +08:00</span></div><div className="world-canvas" ref={canvas} aria-hidden="true"/>{(!ready||fallback)&&<img className="world-fallback" src={selected.image} alt="Blush serum editorial concept" fetchPriority="high"/>}<div className="world-edition"><span>0{index+1}</span><div/><small>0{drops.length}</small></div><motion.div className="world-product" key={selected.id} initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.45}}><p className="eyebrow">{selected.brand} <span> / </span>{selected.category}</p><h2>{mn?selected.mn:selected.name}</h2><p>{t('Онцгой цуглуулгын концепц.\nШинэ нээлт бүр — өөрийн мөчтэй.','An exclusive collection concept.\nEvery new release has its own moment.')}</p><Link className="button black" href={'/drops/'+selected.id}>{t('Дроптой танилцах','Discover the drop')}<Plus size={16}/></Link><small>{t('КОНЦЕПЦ • ХУДАЛДАН АВАЛТ НЭЭГДЭЭГҮЙ','CONCEPT • PURCHASING NOT OPEN')}</small></motion.div><div className="world-controls"><button aria-label={t('Өмнөх дроп','Previous drop')} onClick={()=>select(index-1)} disabled={index===0}><ChevronLeft size={19}/></button><div role="group" aria-label={t('Дроп сонгох','Choose a drop')}>{drops.map((d,i)=><button key={d.id} aria-label={mn?d.mn:d.name} aria-pressed={i===index} className={i===index?'selected':''} onClick={()=>select(i)}><span>0{i+1}</span></button>)}</div><button aria-label={t('Дараагийн дроп','Next drop')} onClick={()=>select(index+1)} disabled={index===drops.length-1}><ChevronRight size={19}/></button></div><div className="world-bottom"><span>LIMITED BY TIME. REMEMBERED FOREVER.</span><span className="world-scroll">{t('ГҮЙЛГЭЖ ДРОПУУДЫГ НЭЭХ','SCROLL TO DISCOVER')}<ArrowDown size={15}/></span><a href="#next-drops" className="world-skip">{t('Цуглуулга үзэх','View collection')}<MoveUpRight size={15}/></a></div><div className="world-progress" style={{transform:`scaleX(${(index+1)/drops.length})`}}/></div></section>;
}
