'use client';
import {useMemo,useState} from 'react';
import Link from './site-link';
import BeautyWorld from './beauty-world';
import CollectionArt from './collection-art';
import Countdown from './drop-countdown';
import BrandProfile from './brand-profile';
import {BrandBackdrop,brandStyle} from './brand-theme';
import {findDirectoryBrand} from '@/lib/brand-directory';
import {effectiveStatus,money} from '@/lib/catalog';
import type {CommerceDrop} from '@/lib/commerce-types';
export default function BrandCollection({brand,catalog,mn}:{brand:string;catalog:CommerceDrop[];mn:boolean}){const [showStage,setShowStage]=useState(true),products=useMemo(()=>catalog.filter(d=>d.brand===brand||d.brand===findDirectoryBrand(brand)?.name),[catalog,brand]),t=(a:string,b:string)=>mn?a:b;const directoryBrand=findDirectoryBrand(brand);if(!products.length&&directoryBrand)return <BrandProfile brand={directoryBrand} mn={mn}/>;if(!products.length)return <section className="section"><h1>{brand}</h1><p>{t('Энэ цуглуулга одоогоор нийтлэгдээгүй.','This collection is not currently published.')}</p><Link href="/brands" className="button outline">{t('Брэндүүд','Brands')}</Link></section>;return <div className={directoryBrand?"brand-collection-world":undefined} style={directoryBrand?brandStyle(directoryBrand):undefined}>{directoryBrand&&<BrandBackdrop brand={directoryBrand}/>}<div className="brand-navigation"><Link href="/brands">{t('Бүх брэнд','All brands')}</Link><span>{directoryBrand?.name||brand} / {products.length} {t('цуглуулга','collections')}</span><div><button aria-pressed={showStage} onClick={()=>setShowStage(true)}>3D</button><button aria-pressed={!showStage} onClick={()=>setShowStage(false)}>{t('Цуглуулга','Collection')}</button></div></div>{showStage?<BeautyWorld mn={mn} catalog={products}/>:<section className="section listing"><div className="page-heading"><p className="eyebrow">THE BRAND COLLECTION</p><h1>{directoryBrand?.name||brand}</h1><p>{products.every(d=>d.approved)?t('Батлагдсан, хугацаатай онцгой нээлтүүд.','Approved releases with official purchase windows.'):t('Редакцын концепц цуглуулгууд.','Editorial concept collections.')}</p></div><div className="drop-grid">{products.map(d=>{const status=effectiveStatus(d);return <article key={d.id} className={'drop-card '+d.tone}><Link href={'/drops/'+d.id} className="card-image"><CollectionArt drop={d}/><span className="image-label">{d.approved?status:'CONCEPT'}</span></Link><div className="card-meta"><span>{d.category}</span><span>{money(d.price)}</span></div><Link className="card-name" href={'/drops/'+d.id}>{mn?d.mn:d.name}</Link><Countdown compact mn={mn} phase={status==='UPCOMING'?'opening':'closing'} target={status==='UPCOMING'?d.opensAt:d.closesAt} closed={['CLOSED','ARCHIVED'].includes(status)}/><Link className="text-link" href={'/drops/'+d.id}>{t('Дроптой танилцах','Discover drop')}</Link></article>})}</div></section>}</div>}
