'use client';
import {useState} from 'react';
import Link from './site-link';
const errors:Record<string,[string,string]>={INVALID_INPUT:['Зөв имэйл хаяг болон 12–128 тэмдэгттэй нууц үг оруулна уу.','Enter a valid email and a password of 12–128 characters.'],INVALID_CREDENTIALS:['Имэйл эсвэл нууц үг буруу байна.','Email or password is incorrect.'],INVALID_ORIGIN:['Хуудсаа шинэчлээд дахин оролдоно уу.','Refresh the page and try again.'],ACCOUNT_UNAVAILABLE:['Энэ бүртгэлийг үүсгэх боломжгүй. Нэвтрэх эсвэл тусламж авахыг оролдоно уу.','Could not create this account. Try signing in or contact support.'],BODY_TOO_LARGE:['Мэдээлэл хэт урт байна.','Request too large.'],RATE_LIMITED:['Хэт олон оролдлого хийлээ. 15 минутын дараа дахин оролдоно уу.','Too many attempts. Try again in 15 minutes.'],UNAVAILABLE:['Нэвтрэх үйлчилгээ түр боломжгүй байна. Дахин оролдоно уу.','Sign-in is temporarily unavailable. Please retry.'],TERMS_REQUIRED:['Бүртгүүлэхийн тулд үйлчилгээний болон нууцлалын нөхцөлийг зөвшөөрнө үү.','Accept the terms and privacy policy to register.']};
export default function EmailAccountForm({mn,onSignedIn}:{mn:boolean;onSignedIn:()=>Promise<void>}){
 const [mode,setMode]=useState<'login'|'register'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[acceptTerms,setAcceptTerms]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const t=(a:string,b:string)=>mn?a:b;
 return <form className="email-signin" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,action:mode,acceptTerms})});const j=await r.json() as {code?:string};if(!r.ok)throw new Error(j.code||'UNAVAILABLE');setPassword('');await onSignedIn()}catch(e){setError((errors[(e as Error).message]||errors.UNAVAILABLE)[mn?0:1])}finally{setBusy(false)}}}>
 <h3>{mode==='login'?t('Нэвтрэх','Sign in'):t('Бүртгүүлэх','Create an account')}</h3>
 <label>{t('Имэйл хаяг','Email address')}<input name="email" type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} placeholder="you@example.com"/></label>
 <label>{t('Нууц үг','Password')}<input name="password" type="password" required autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={12} maxLength={128}/></label>
 <p className="subtle-notice">{t('Нууц үг 12–128 тэмдэгт байна.','Use a password of 12–128 characters.')}</p>
 {mode==='register'&&<label className="profile-consent account-agreement"><input type="checkbox" required checked={acceptTerms} onChange={e=>setAcceptTerms(e.target.checked)}/><span>{t('Би үйлчилгээний болон нууцлалын нөхцөлийг зөвшөөрч байна.','I agree to the terms and privacy policy.')} <Link href="/policies">{t('Нөхцөл ба нууцлал','Terms & privacy')}</Link></span></label>}
 {error&&<p role="alert" className="order-error">{error}</p>}
 <button className="button black full" disabled={busy}>{busy?t('Түр хүлээнэ үү…','Please wait…'):mode==='login'?t('Нэвтрэх','Sign in'):t('Бүртгүүлэх','Create account')}</button>
 <button type="button" className="text-link" disabled={busy} onClick={()=>{setMode(mode==='login'?'register':'login');setError('');setPassword('');setAcceptTerms(false)}}>{mode==='login'?t('Шинэ хэрэглэгч үү? Бүртгүүлэх','New here? Create an account'):t('Бүртгэлтэй юу? Нэвтрэх','Already registered? Sign in')}</button>
 <p className="subtle-notice">{t('Имэйл баталгаажуулалт болон нууц үг сэргээх үйлчилгээ одоогоор идэвхгүй. Нэвтрэх имэйл, нууц үгээ найдвартай хадгална уу.','Email verification and password recovery are not available yet. Keep your login details safe.')}</p>
 </form>
}
