'use client';
import {useEffect,useRef,useState} from 'react';
import {RotateCcw,Box,ImageIcon} from 'lucide-react';
export default function ProductViewer({index=0,image,url,dropId}:{index?:number;image?:string;url?:string;dropId?:string}){
 const host=useRef<HTMLDivElement>(null),engine=useRef<ReturnType<typeof import('@/lib/three/product-scene').createProductScene>|null>(null);const [photo,setPhoto]=useState(false),[failed,setFailed]=useState(false),[ready,setReady]=useState(false),[approvedUrl,setApprovedUrl]=useState<string>();
 useEffect(()=>{if(!dropId)return;let alive=true;fetch('/api/models/public?drop='+encodeURIComponent(dropId)).then(r=>r.json()).then((j:any)=>{if(alive&&j.url)setApprovedUrl(j.url)}).catch(()=>{});return()=>{alive=false}},[dropId]);
 useEffect(()=>{let active=true;setFailed(false);setReady(false);if(photo||!host.current)return;import('@/lib/three/product-scene').then(m=>{if(!active||!host.current)return;try{engine.current=m.createProductScene(host.current,{index,url:url||approvedUrl,onReady:()=>active&&setReady(true),onError:()=>active&&setFailed(true)})}catch{setFailed(true)}}).catch(()=>active&&setFailed(true));return()=>{active=false;engine.current?.dispose();engine.current=null}},[index,url,approvedUrl,photo]);
 return <div className="product-viewer"><div className="viewer-host" ref={host}/>{(photo||failed)&&image&&<img className="viewer-photo" src={image} alt="Editorial product photograph"/>}<div className="viewer-top"><span><Box size={13}/>{url||approvedUrl?'3D MODEL':'3D CONCEPT'}</span><span>360°</span></div>{!ready&&!photo&&!failed&&<span className="viewer-loading">LOADING 3D…</span>}{failed&&!image&&<p className="viewer-loading" role="alert">Unable to render this model.</p>}<div className="viewer-tools"><span>{photo?'EDITORIAL PHOTOGRAPH':'DRAG TO ROTATE'}</span><div><button aria-label="Reset 3D view" disabled={photo||failed} onClick={()=>engine.current?.reset()}><RotateCcw size={16}/></button>{image&&<button aria-label={photo?'Show 3D':'Show photograph'} onClick={()=>setPhoto(!photo)}>{photo?<Box size={16}/>:<ImageIcon size={16}/>}</button>}</div></div></div>
}
