'use client';
import {useEffect,useRef,useState} from 'react';
import {RotateCcw,Box,ImageIcon} from 'lucide-react';
export default function ProductViewer({index=0,image,url,dropId,approved=false}:{index?:number;image?:string;url?:string;dropId?:string;approved?:boolean}){
 const host=useRef<HTMLDivElement>(null),engine=useRef<ReturnType<typeof import('@/lib/three/product-scene').createProductScene>|null>(null);const [photo,setPhoto]=useState(false),[failed,setFailed]=useState(false),[ready,setReady]=useState(false),[approvedUrl,setApprovedUrl]=useState<string>(),[resolved,setResolved]=useState(!dropId),[retry,setRetry]=useState(0),[imageFailed,setImageFailed]=useState(false);
 useEffect(()=>{setApprovedUrl(undefined);setResolved(!dropId);setPhoto(false);setImageFailed(false);if(!dropId)return;let alive=true;const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),10000);fetch('/api/models/public?drop='+encodeURIComponent(dropId),{signal:abort.signal}).then(r=>r.ok?r.json():null).then((j:any)=>{if(alive&&j?.url)setApprovedUrl(j.url)}).catch(()=>{}).finally(()=>{clearTimeout(timer);if(alive)setResolved(true)});return()=>{alive=false;clearTimeout(timer);abort.abort()}},[dropId,retry]);
 const modelUrl=url||approvedUrl,needsModel=approved&&!modelUrl,showPhoto=photo||failed||needsModel;
 useEffect(()=>{let active=true;setFailed(false);setReady(false);if(photo||!host.current||(!url&&!resolved)||needsModel)return;const timeout=setTimeout(()=>active&&setFailed(true),22000);import('@/lib/three/product-scene').then(m=>{if(!active||!host.current)return;try{engine.current=m.createProductScene(host.current,{index,url:modelUrl,onReady:()=>{clearTimeout(timeout);if(active)setReady(true)},onError:()=>{clearTimeout(timeout);if(active)setFailed(true)}})}catch{clearTimeout(timeout);if(active)setFailed(true)}}).catch(()=>{clearTimeout(timeout);if(active)setFailed(true)});return()=>{active=false;clearTimeout(timeout);engine.current?.dispose();engine.current=null}},[index,modelUrl,photo,resolved,needsModel,retry,url]);
 return <div className="product-viewer"><div className="viewer-host" ref={host}/>{(!ready||showPhoto)&&image&&!imageFailed&&<img className="viewer-photo" src={image} alt="Product photograph" decoding="async" onError={()=>setImageFailed(true)}/>}<div className="viewer-top"><span><Box size={13}/>{showPhoto?'PRODUCT PHOTOGRAPH':modelUrl?'PRODUCT / 3D':'EDITORIAL / 3D CONCEPT'}</span><span>{ready&&!showPhoto?'360°':'PHOTO'}</span></div>{!ready&&!showPhoto&&<span className="viewer-loading" role="status">LOADING 3D…</span>}{imageFailed&&showPhoto&&<p className="viewer-loading" role="status">Product media is temporarily unavailable.</p>}<div className="viewer-tools"><span>{showPhoto?'PRODUCT PHOTOGRAPH':'DRAG TO ROTATE'}</span><div><button aria-label="Reset 3D view" disabled={!ready||showPhoto} onClick={()=>engine.current?.reset()}><RotateCcw size={16}/></button>{failed&&<button aria-label="Retry loading model" onClick={()=>{setFailed(false);setRetry(n=>n+1)}}><RotateCcw size={16}/></button>}{image&&<button aria-label={photo?'Show 3D':'Show photograph'} disabled={needsModel||failed} onClick={()=>setPhoto(!photo)}>{photo?<Box size={16}/>:<ImageIcon size={16}/>}</button>}</div></div></div>
}
