import {directoryBrands} from './brand-directory';
import {CommerceError} from './commerce-types';
export function importHost(brandId:string){const brand=directoryBrands.find(b=>b.id===brandId);if(!brand?.logoSource)return null;const host=new URL(brand.logoSource).hostname.replace(/^www\./,'');return host==='cdn.shopify.com'?null:host}
export function sourceUrl(raw:string,host:string){let u:URL;try{u=new URL(raw)}catch{throw new CommerceError('Invalid source URL',400)}if(u.protocol!=='https:'||u.username||u.password||(u.port&&u.port!=='443')||!([host,'www.'+host].includes(u.hostname)))throw new CommerceError('Use the selected brand’s HTTPS website only',400);u.hash='';return u}
function plain(value:unknown,max=12000){return typeof value==='string'?value.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,max):''}
export function parseProduct(html:string,url:string){const nodes:any[]=[];function visit(x:any){if(Array.isArray(x))x.forEach(visit);else if(x&&typeof x==='object'){nodes.push(x);if(x['@graph'])visit(x['@graph']);if(x.mainEntity)visit(x.mainEntity)}}for(const m of html.matchAll(/<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script\s*>/gi)){try{visit(JSON.parse(m[1]))}catch{/* Broken third-party structured data remains ignored. */}}
const p=nodes.find(n=>(Array.isArray(n['@type'])?n['@type']:[n['@type']]).includes('Product'));if(!p||!plain(p.name,300))throw new CommerceError('No usable Product structured data found. Use the manual import for this page.',422);
const offers=[].concat(p.offers||[]).slice(0,50).map((o:any)=>({sku:plain(o.sku,150),price:plain(String(o.price??''),100),currency:plain(o.priceCurrency,10),availability:plain(o.availability,200)}));const images=[].concat(p.image||[]).map((x:any)=>typeof x==='string'?x:x?.url).filter((x:any)=>typeof x==='string').map((x:string)=>{try{const u=new URL(x,url);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}).filter(Boolean).slice(0,12);
const colour=html.match(/<meta\b[^>]*name=["']theme-color["'][^>]*content=["'](#[0-9a-f]{3,8})["']/i)?.[1];return {name:plain(p.name,300),description:plain(p.description),brand:plain(typeof p.brand==='string'?p.brand:p.brand?.name,200),sku:plain(p.sku,150),images,offers,themeColor:colour||null,sourceUrl:url,fetchedAt:new Date().toISOString(),publicationApproved:false,mediaRightsApproved:false};}
export async function importWebsite(brandId:string,raw:string){const host=importHost(brandId);if(!host)throw new CommerceError('This brand’s import domain is not configured; use a structured manual import.',400);let url=sourceUrl(raw,host);for(let hop=0;hop<4;hop++){const response=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(12000),headers:{Accept:'text/html','User-Agent':'MNDrop-ProductReview/1.0'}});if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');if(!location)throw new CommerceError('Invalid website redirect',422);url=sourceUrl(new URL(location,url).href,host);continue}if(!response.ok||!(response.headers.get('content-type')||'').includes('text/html'))throw new CommerceError('Website blocked the import or returned unsupported content. Use manual import.',422);const reader=response.body?.getReader();if(!reader)throw new CommerceError('Empty source',422);let bytes=0,html='';const decoder=new TextDecoder();try{while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>2000000)throw new CommerceError('Source page exceeds import limit',413);html+=decoder.decode(value,{stream:true})}html+=decoder.decode();return parseProduct(html,url.href)}finally{await reader.cancel().catch(()=>{})}}throw new CommerceError('Too many website redirects',422)}
