export type CampaignStatus = 'DRAFT' | 'EMBARGO' | 'UPCOMING' | 'LIVE' | 'CLOSED' | 'ARCHIVED';
export type Drop = {id:string;brand:string;name:string;mn:string;category:string;description:string;descriptionMn:string;price:number;tone:string;opensAt:string;closesAt:string;status:CampaignStatus;approved:boolean;image:string;variants:string[]};
// Editorial concept fixtures: no partner authorization, real stock, or availability is implied.
export const drops:Drop[] = [
{id:'petal-reset',brand:'ATELIER 01',name:'The Petal Reset',mn:'Арьсны шинэ эхлэл',category:'SKINCARE',description:'A considered daily ritual. A luminous serum concept with a weightless finish and a quietly beautiful presence.',descriptionMn:'Өдөр тутмын арчилгааг онцгой мөч болгох хөнгөн бүтэцтэй серумын концепц.',price:189000,tone:'pink',opensAt:'2026-10-08T00:00:00+08:00',closesAt:'2026-10-12T20:00:00+08:00',status:'LIVE',approved:false,image:'/petal-reset.webp',variants:['30 ml','50 ml']},
{id:'blue-hour',brand:'ATELIER 02',name:'The Blue Hour',mn:'Цэнхэр цагийн арчилгаа',category:'HYDRATION',description:'A new perspective on the evening ritual. Discover an editorial hydration collection.',descriptionMn:'Оройн арчилгааг шинэ мэдрэмжээр. Чийгшүүлэх цуглуулгын концепц.',price:149000,tone:'blue',opensAt:'2026-10-18T20:00:00+08:00',closesAt:'2026-10-21T20:00:00+08:00',status:'UPCOMING',approved:false,image:'/blue-hour.webp',variants:['50 ml']},
{id:'soft-focus',brand:'ATELIER 03',name:'Soft Focus',mn:'Зөөлөн туяа',category:'MAKEUP',description:'Soft colour, expressive texture. A modern approach to a beauty essential.',descriptionMn:'Зөөлөн өнгө, торгомсог мэдрэмж. Гоо сайхны өдөр тутмын сонголтын концепц.',price:99000,tone:'rose',opensAt:'2026-10-24T20:00:00+08:00',closesAt:'2026-10-28T20:00:00+08:00',status:'UPCOMING',approved:false,image:'/campaign.jpg',variants:['Rose','Petal','Nude']},
{id:'golden-ritual',brand:'ATELIER 04',name:'Golden Ritual',mn:'Алтан мөч',category:'BODY CARE',description:'An invitation to slow down. A warm, sensorial body-care concept.',descriptionMn:'Өөртөө цаг гаргах урилга. Дулаан мэдрэмжтэй бие арчилгааны концепц.',price:129000,tone:'gold',opensAt:'2026-11-02T20:00:00+08:00',closesAt:'2026-11-06T20:00:00+08:00',status:'UPCOMING',approved:false,image:'/campaign.jpg',variants:['100 ml']},
{id:'first-light',brand:'ATELIER 01',name:'First Light',mn:'Анхны гэрэл',category:'ARCHIVE',description:'The beginning of a new ritual. An archived editorial concept, permanently closed.',descriptionMn:'Арчилгааны шинэ эхлэл. Архивлагдсан концепц; худалдан авах боломжгүй.',price:169000,tone:'gray',opensAt:'2026-09-01T20:00:00+08:00',closesAt:'2026-09-06T20:00:00+08:00',status:'ARCHIVED',approved:false,image:'/campaign.jpg',variants:['30 ml']}
];
export function effectiveStatus(d:Pick<Drop,'status'|'opensAt'|'closesAt'>,now=Date.now()):CampaignStatus {if(['CLOSED','ARCHIVED','DRAFT','EMBARGO'].includes(d.status))return d.status;if(now>=Date.parse(d.closesAt))return 'CLOSED';if(now<Date.parse(d.opensAt))return 'UPCOMING';return d.status;}
export function canPurchase(d:Drop,now=Date.now()){return d.approved && d.status==='LIVE' && now>=Date.parse(d.opensAt) && now<Date.parse(d.closesAt);}
export const money=(n:number)=>new Intl.NumberFormat('en-US').format(n)+' ₮';
export const lifecycle=['PRE_ORDER','CONSOLIDATED','BRAND_ORDER','INTERNATIONAL_SHIPPING','MONGOLIA','DELIVERED'];
export const transition:Record<CampaignStatus,CampaignStatus[]>={DRAFT:['EMBARGO','UPCOMING'],EMBARGO:['UPCOMING'],UPCOMING:['LIVE','CLOSED'],LIVE:['CLOSED'],CLOSED:['ARCHIVED'],ARCHIVED:[]};
