import {database} from '@/db/raw';
import {CommerceError,textValue,positive} from './commerce-types';
import {statement,one,rows,iso,orderDetail,mailJob} from './commerce-store';
import {configuration} from './runtime-config';
import {paymentReady,issueInvoice,digest,providerPayments,cancelInvoice} from './commerce-payments';
import {verifiedReceipts} from './settlement-contract';
export async function reserveCheckout(input:any,user:{userId:string;email:string}){
 if(!paymentReady())throw new CommerceError('QPay merchant checkout is not configured and sandbox-verified yet',503);
 const key=textValue(input.idempotencyKey,80);if(!/^[a-f0-9-]{36}$/i.test(key))throw new CommerceError('Checkout idempotency key required',400);const idempotency=user.userId+':'+key;
 const previous=await one('SELECT order_id FROM commerce_order_meta WHERE idempotency=?',idempotency);if(previous)return orderDetail(previous.order_id,user.userId);
 if(!Array.isArray(input.items)||input.items.length<1||input.items.length>30)throw new CommerceError('Invalid cart',400);
 if(input.acceptedTerms!==true)throw new CommerceError('Campaign terms consent required',400);const address:any={};for(const field of ['name','phone','city','district','street']){address[field]=textValue(input.address?.[field],field==='street'?500:100);if(!address[field])throw new CommerceError('Complete delivery details required',400)}if(!/^\+?[0-9 ()-]{8,20}$/.test(address.phone))throw new CommerceError('Invalid phone number',400);
 const products=[];const ids=new Set<string>();for(const item of input.items){const v=await one('SELECT v.*,c.status,c.opens_at,c.closes_at,c.approved_by,c.closed_at,m.review_by FROM commerce_variants v JOIN campaigns c ON c.id=v.campaign_id JOIN commerce_content m ON m.campaign_id=c.id WHERE v.campaign_id=? AND v.label=?',textValue(item.drop_id,100),textValue(item.variant,100));const q=positive(item.quantity,1000);if(!v||ids.has(v.id)||v.status!=='LIVE'||!v.review_by||!v.approved_by||v.closed_at||Date.now()<Date.parse(v.opens_at)||Date.now()>=Date.parse(v.closes_at)||q>v.max_per_customer||v.reserved+v.paid_qty+q>v.allocation)throw new CommerceError('Drop closed, duplicate variant or allocation exceeded');ids.add(v.id);products.push({...v,quantity:q,lineId:crypto.randomUUID()})}
 const campaign=products[0].campaign_id;const policy=await one('SELECT content FROM commerce_content WHERE campaign_id=?',campaign);const content=JSON.parse(policy.content);address.consent={acceptedAt:iso(),refundEn:content.refundEn,refundMn:content.refundMn,deliveryEn:content.deliveryEn,deliveryMn:content.deliveryMn};if(products.some(v=>v.campaign_id!==campaign))throw new CommerceError('Checkout one drop at a time; drops have separate deadlines');
 const id=crypto.randomUUID(),secret=crypto.randomUUID()+crypto.randomUUID(),now=iso(),expires=new Date(Math.min(Date.now()+900000,Date.parse(products[0].closes_at))).toISOString(),total=products.reduce((n,v)=>n+v.quantity*v.price_mnt,0);if(!Number.isSafeInteger(total)||total<=0||total>2147483647)throw new CommerceError('Invalid order total');
 const statements=[statement("INSERT INTO orders(id,user_id,campaign_id,status,total_mnt,created_at) SELECT ?,?,?,?, ?,? FROM campaigns c JOIN commerce_content m ON m.campaign_id=c.id WHERE c.id=? AND c.status='LIVE' AND c.closed_at IS NULL AND c.approved_by IS NOT NULL AND m.review_by IS NOT NULL AND c.opens_at<=? AND c.closes_at>?",id,user.userId,campaign,'PAYMENT_PENDING',total,now,campaign,now,now),statement('INSERT INTO commerce_order_meta(order_id,email,address,expires_at,idempotency,callback_hash) VALUES(?,?,?,?,?,?)',id,user.email,JSON.stringify(address),expires,idempotency,await digest(secret)),statement('INSERT INTO commerce_events(id,order_id,state,note,created_at) VALUES(?,?,?,?,?)',crypto.randomUUID(),id,'PAYMENT_PENDING','QPay invoice requested; payment unverified',now)];
 for(const v of products)statements.push(statement('UPDATE commerce_variants SET reserved=reserved+? WHERE id=?',v.quantity,v.id),statement('INSERT INTO commerce_usage(user_id,variant_id,quantity,max_quantity) VALUES(?,?,?,?) ON CONFLICT(user_id,variant_id) DO UPDATE SET quantity=commerce_usage.quantity+excluded.quantity',user.userId,v.id,v.quantity,v.max_per_customer),statement('INSERT INTO order_lines(id,order_id,sku,variant,quantity,unit_mnt) VALUES(?,?,?,?,?,?)',v.lineId,id,v.sku,v.label,v.quantity,v.price_mnt),statement('INSERT INTO commerce_line_variants(line_id,variant_id) VALUES(?,?)',v.lineId,v.id));
 try{await database().batch(statements)}catch{const existing=await one('SELECT order_id FROM commerce_order_meta WHERE idempotency=?',idempotency);if(existing)return orderDetail(existing.order_id,user.userId);throw new CommerceError('Allocation or customer limit changed. Refresh your bag and retry')}
 // Invoice creation is deliberately never blindly retried. A timeout can mean the
 // provider accepted it; the pending order keeps its reservation for reconciliation.
 const callback=new URL('/api/payments/callback',configuration().APP_URL);callback.searchParams.set('order',id);callback.searchParams.set('token',secret);
 try{const invoice=await issueInvoice(id,total,callback.toString());await statement('UPDATE commerce_order_meta SET invoice_id=?,invoice_data=? WHERE order_id=?',invoice.invoice_id,JSON.stringify(invoice),id).run()}catch{await statement('INSERT INTO commerce_events(id,order_id,state,note,created_at) VALUES(?,?,?,?,?)',crypto.randomUUID(),id,'INVOICE_RECONCILIATION','Invoice creation response unavailable; support must reconcile before retry',iso()).run()}
 return orderDetail(id,user.userId)
}
async function reservationLines(id:string){return rows('SELECT l.quantity,lv.variant_id,o.user_id FROM order_lines l JOIN commerce_line_variants lv ON lv.line_id=l.id JOIN orders o ON o.id=l.order_id WHERE l.order_id=?',id)}
export async function receivePayment(id:string,secret:string){const meta=await one('SELECT m.*,o.status,o.total_mnt,o.user_id,c.status AS campaign_status,c.closes_at FROM commerce_order_meta m JOIN orders o ON o.id=m.order_id JOIN campaigns c ON c.id=o.campaign_id WHERE m.order_id=?',id);if(!meta||await digest(secret)!==meta.callback_hash)throw new CommerceError('Invalid callback token',403);if(!meta.invoice_id)throw new CommerceError('Invoice requires reconciliation',503);if(meta.status==='PAID'||meta.status==='REFUND_REQUIRED')return {received:true};const payments=await providerPayments(meta.invoice_id);if(!payments.length)return {received:true,paid:false};let receipts;try{receipts=verifiedReceipts(payments,meta.invoice_id,meta.total_mnt)}catch{throw new CommerceError('Verified payment response failed invoice/currency/amount checks',409)}
 const eligible=meta.status==='PAYMENT_PENDING'&&meta.campaign_status==='LIVE'&&Date.parse(meta.expires_at)>Date.now()&&Date.parse(meta.closes_at)>Date.now(),state=eligible?'PAID':'REFUND_REQUIRED',lines=await reservationLines(id),now=iso();const existingDecision=await one('SELECT state FROM commerce_decisions WHERE order_id=?',id);const statements=[];
 if(!existingDecision)statements.push(statement("INSERT INTO commerce_decisions(order_id,state,valid) VALUES(?,?,(SELECT CASE WHEN o.status='PAYMENT_PENDING' AND (?<>'PAID' OR (m.expires_at>? AND c.closes_at>? AND c.status='LIVE')) THEN 1 ELSE 0 END FROM orders o JOIN commerce_order_meta m ON m.order_id=o.id JOIN campaigns c ON c.id=o.campaign_id WHERE o.id=?))",id,state,state,now,now,id));else if(existingDecision.state!=='EXPIRED')return {received:true};
 for(const receipt of receipts)statements.push(statement('INSERT INTO commerce_receipts(payment_id,order_id,amount_mnt,verified_at,evidence) VALUES(?,?,?,?,?)',receipt.id,id,receipt.amount,now,receipt.evidence));
 statements.push(statement('INSERT INTO commerce_events(id,order_id,state,note,created_at) VALUES(?,?,?,?,?)',crypto.randomUUID(),id,state,eligible?'Provider verified exact MNT payment':'Late verified payment; human refund reconciliation required',now),statement('UPDATE orders SET status=?,payment_reference=? WHERE id=?',state,receipts.map(x=>x.id).join(','),id));
 if(!existingDecision)for(const l of lines){statements.push(statement('UPDATE commerce_variants SET reserved=reserved-?,paid_qty=paid_qty+? WHERE id=?',l.quantity,eligible?l.quantity:0,l.variant_id));if(!eligible)statements.push(statement('UPDATE commerce_usage SET quantity=quantity-? WHERE user_id=? AND variant_id=?',l.quantity,l.user_id,l.variant_id))}
 if(eligible)statements.push(statement("DELETE FROM customer_items WHERE user_id=? AND kind='cart' AND drop_id=(SELECT campaign_id FROM orders WHERE id=?)",meta.user_id,id));
 statements.push(mailJob(meta.email,eligible?'Payment confirmed / Төлбөр баталгаажлаа':'Payment review / Төлбөрийн шалгалт',id+'\n'+state));try{await database().batch(statements)}catch{const current=await one('SELECT status FROM orders WHERE id=?',id);if(current?.status==='PAID'||current?.status==='REFUND_REQUIRED')return {received:true};throw new CommerceError('Settlement conflict; callback must retry',503)}return {received:true}
}
export async function expireInvoice(id:string,force=false){const meta=await one('SELECT m.*,o.status FROM commerce_order_meta m JOIN orders o ON o.id=m.order_id WHERE m.order_id=?',id);if(!meta||meta.status!=='PAYMENT_PENDING'||(!force&&Date.parse(meta.expires_at)>Date.now()))return;if(!meta.invoice_id)throw new CommerceError('Missing provider invoice requires human reconciliation');await cancelInvoice(meta.invoice_id);const lines=await reservationLines(id),now=iso();await database().batch([statement("INSERT INTO commerce_decisions(order_id,state,valid) VALUES(?, ?, (SELECT CASE WHEN status='PAYMENT_PENDING' THEN 1 ELSE 0 END FROM orders WHERE id=?))",id,'EXPIRED',id),statement("UPDATE orders SET status='EXPIRED' WHERE id=? AND status='PAYMENT_PENDING'",id),statement('INSERT INTO commerce_events(id,order_id,state,note,created_at) VALUES(?,?,?,?,?)',crypto.randomUUID(),id,'EXPIRED','Provider invoice cancelled; reservation released',now),...lines.flatMap(l=>[statement('UPDATE commerce_variants SET reserved=reserved-? WHERE id=?',l.quantity,l.variant_id),statement('UPDATE commerce_usage SET quantity=quantity-? WHERE user_id=? AND variant_id=?',l.quantity,l.user_id,l.variant_id)])])}
