import type {Drop} from './catalog';
export type CampaignContent={titleMn:string;descriptionEn:string;descriptionMn:string;category:string;image:string;logo:string;modelId:string;environment:number;embargoAt:string;refundEn:string;refundMn:string;deliveryEn:string;deliveryMn:string;sourcingEn:string;sourcingMn:string;ingredientsEn:string;ingredientsMn:string;usageEn:string;usageMn:string;authorizationId:string;variants:{id:string;sku:string;label:string;priceMnt:number;mapMnt:number;allocation:number;moq:number;maxPerCustomer:number}[]};
export type CommerceDrop=Drop & {content?:CampaignContent;variantRecords?:{id:string;label:string;priceMnt:number;remaining:number;maxPerCustomer:number}[];logo?:string;modelId?:string;environment?:number};
export const shipmentStates=['PRE_ORDER','CONSOLIDATED','BRAND_ORDER','INTERNATIONAL_SHIPPING','MONGOLIA','DELIVERED','ARCHIVED'];
export class CommerceError extends Error{constructor(message:string,readonly status=409){super(message)}}
export function textValue(v:unknown,max=4000){if(typeof v!=='string'||v.length>max)throw new CommerceError('Invalid text',400);return v.trim()}
export function positive(v:unknown,max=100000000){const n=Number(v);if(!Number.isSafeInteger(n)||n<1||n>max)throw new CommerceError('Invalid positive integer',400);return n}
export function approvedImage(value:string){if(value.startsWith('/api/media?id=')||value.startsWith('/api/models/file?id='))return true;try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password}catch{return false}}
export function validateContent(input:any):CampaignContent{
 const required=['titleMn','descriptionEn','descriptionMn','category','image','refundEn','refundMn','deliveryEn','deliveryMn','sourcingEn','sourcingMn','ingredientsEn','ingredientsMn','usageEn','usageMn','authorizationId'];const result:any={};for(const k of required){result[k]=textValue(input[k],k==='image'?2048:4000);if(!result[k])throw new CommerceError('Required campaign field: '+k,400)}
 if(!approvedImage(result.image))throw new CommerceError('Approved HTTPS media or uploaded media required',400);for(const k of ['logo','modelId','embargoAt'])result[k]=textValue(input[k]||'',2048);if(result.logo&&!approvedImage(result.logo))throw new CommerceError('Invalid brand logo',400);if(result.embargoAt&&!Number.isFinite(Date.parse(result.embargoAt)))throw new CommerceError('Invalid embargo timestamp',400);result.environment=Math.max(0,Math.min(4,Number(input.environment)||0));
 if(!Array.isArray(input.variants)||input.variants.length<1||input.variants.length>40)throw new CommerceError('1–40 approved variants are required',400);const keys=new Set<string>();result.variants=input.variants.map((v:any)=>{const sku=textValue(v.sku,100),label=textValue(v.label,100);if(!sku||!label||keys.has(sku+'\0'+label))throw new CommerceError('SKU and variant must be unique',400);keys.add(sku+'\0'+label);const priceMnt=positive(v.priceMnt),mapMnt=Number(v.mapMnt);if(!Number.isSafeInteger(mapMnt)||mapMnt<0||priceMnt<mapMnt)throw new CommerceError('Price is below approved MAP',400);return {id:crypto.randomUUID(),sku,label,priceMnt,mapMnt,allocation:positive(v.allocation,1000000),moq:positive(v.moq,1000000),maxPerCustomer:positive(v.maxPerCustomer,1000)}});return result;
}
