import {configuration} from './runtime-config';
import {CommerceError} from './commerce-types';
let token:{value:string;expires:number}|undefined;
export function paymentReady(){const c=configuration();return !!(c.QPAY_USERNAME&&c.QPAY_PASSWORD&&c.QPAY_INVOICE_CODE&&c.QPAY_RECEIVER_CODE&&c.APP_URL&&c.QPAY_MAPPER_REVIEWED==='true')}
function host(){const b=configuration().QPAY_BASE_URL||'https://merchant-sandbox.qpay.mn';if(!['https://merchant.qpay.mn','https://merchant-sandbox.qpay.mn'].includes(b))throw new CommerceError('Unapproved QPay host',503);return b}
async function access(){if(!paymentReady())throw new CommerceError('Merchant checkout requires credentials and reviewed sandbox response fixtures',503);if(token&&token.expires>Date.now())return token.value;const c=configuration(),r=await fetch(host()+'/v2/auth/token',{method:'POST',headers:{Authorization:'Basic '+btoa(c.QPAY_USERNAME+':'+c.QPAY_PASSWORD)},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new CommerceError('Payment provider temporarily unavailable',503);const j:any=await r.json();if(typeof j.access_token!=='string'||!Number.isFinite(j.expires_in))throw new CommerceError('Unrecognized merchant authentication response',503);token={value:j.access_token,expires:Date.now()+Math.max(0,j.expires_in-60)*1000};return token.value}
async function call(path:string,method:string,body?:unknown){const auth=await access(),r=await fetch(host()+path,{method,headers:{Authorization:'Bearer '+auth,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new CommerceError('Payment provider request failed; invoice requires reconciliation',503);return r.status===204?{}:r.json()}
export async function issueInvoice(id:string,amount:number,callback:string){const c=configuration(),j:any=await call('/v2/invoice','POST',{invoice_code:c.QPAY_INVOICE_CODE,sender_invoice_no:id,invoice_receiver_code:c.QPAY_RECEIVER_CODE,invoice_description:'BEAUTY DROP '+id,amount,callback_url:callback});if(typeof j.invoice_id!=='string'||j.invoice_id.length>160||typeof j.qr_image!=='string'||j.qr_image.length>1000000||!Array.isArray(j.urls))throw new CommerceError('Invoice response requires merchant schema review',503);return {invoice_id:j.invoice_id,qr_image:j.qr_image,qr_text:typeof j.qr_text==='string'?j.qr_text:'',urls:j.urls.filter((u:any)=>typeof u.name==='string'&&typeof u.link==='string'&&u.link.length<2048&&/^[a-z][a-z0-9+.-]*:/i.test(u.link)&&!/^javascript:|^data:|^file:/i.test(u.link)).map((u:any)=>({name:u.name,link:u.link}))}}
export async function providerPayments(invoiceId:string){const j:any=await call('/v2/payment/check','POST',{object_type:'INVOICE',object_id:invoiceId,offset:{page_number:1,page_limit:100}});if(!Array.isArray(j.rows)||j.rows.length>100)throw new CommerceError('Unrecognized payment check response',503);const result=[];for(const row of j.rows){if(row.payment_status!=='PAID')continue;if(typeof row.payment_id!=='string'||row.payment_id.length>160)throw new CommerceError('Payment identity missing',503);const detail:any=await call('/v2/payment/'+encodeURIComponent(row.payment_id),'GET');result.push(detail)}return result}
export async function cancelInvoice(id:string){await call('/v2/invoice/'+encodeURIComponent(id),'DELETE')}
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(n=>n.toString(16).padStart(2,'0')).join('')}
