import { sqliteTable, text, integer, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const customerItems=sqliteTable('customer_items',{userId:text('user_id').notNull(),kind:text('kind').notNull(),dropId:text('drop_id').notNull(),variant:text('variant').notNull().default(''),quantity:integer('quantity').notNull().default(1),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.userId,t.kind,t.dropId,t.variant]})]);
export const campaigns=sqliteTable('campaigns',{id:text('id').primaryKey(),name:text('name').notNull(),brand:text('brand').notNull(),status:text('status').notNull().default('DRAFT'),opensAt:text('opens_at').notNull(),closesAt:text('closes_at').notNull(),authorizationId:text('authorization_id'),approvedBy:text('approved_by'),closedAt:text('closed_at'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()});
export const authorizations=sqliteTable('authorizations',{id:text('id').primaryKey(),brand:text('brand').notNull(),documentUrl:text('document_url').notNull(),validUntil:text('valid_until').notNull(),createdBy:text('created_by').notNull()});
export const audit=sqliteTable('audit_logs',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),recordId:text('record_id').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),userId:text('user_id').notNull(),campaignId:text('campaign_id').notNull(),status:text('status').notNull().default('PAYMENT_PENDING'),totalMnt:integer('total_mnt').notNull(),paymentReference:text('payment_reference'),createdAt:text('created_at').notNull()},t=>[index('idx_orders_user').on(t.userId),index('idx_orders_status').on(t.status)]);
export const orderLines=sqliteTable('order_lines',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),sku:text('sku').notNull(),variant:text('variant').notNull(),quantity:integer('quantity').notNull(),unitMnt:integer('unit_mnt').notNull()},t=>[index('idx_order_lines_order').on(t.orderId)]);

export const modelJobs=sqliteTable('model_jobs',{id:text('id').primaryKey(),name:text('name').notNull(),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),status:text('status').notNull(),progress:integer('progress').notNull().default(0),sourceKind:text('source_kind').notNull(),providerId:text('provider_id'),assetKey:text('asset_key'),dropId:text('drop_id'),approvedBy:text('approved_by'),approvedAt:text('approved_at'),error:text('error')},t=>[index('idx_model_owner').on(t.createdBy,t.createdAt),index('idx_model_public').on(t.dropId,t.status)]);
