import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database,isAdmin,validOrigin} from '@/db/raw';
import {createCampaign,saveContent,reviewCampaign,changeCampaign,operationsData,preparePo,advanceShipment,statement,audit,iso,one,mailJob} from '@/lib/commerce-store';
import {CommerceError,textValue,approvedImage} from '@/lib/commerce-types';
async function admin(){const u=await getChatGPTUser();return u&&isAdmin(u.email)?u:null}
function failure(e:unknown){console.error('Operations request failed',e instanceof CommerceError?e.message:'Storage/provider failure');return Response.json({error:e instanceof CommerceError?e.message:'Operations temporarily unavailable'},{status:e instanceof CommerceError?e.status:503})}
export async function GET(){if(!await admin())return Response.json({error:'Administrative access required'},{status:403});try{return Response.json(await operationsData())}catch(e){return failure(e)}}
export async function POST(req:Request){if(!validOrigin(req))return Response.json({error:'Invalid origin'},{status:403});const u=await admin();if(!u)return Response.json({error:'Administrative access required'},{status:403});try{const b:any=await req.json();const id=textValue(b.id||'',100);if(b.action==='create')return Response.json(await createCampaign({...b,opensAt:b.opensAt+'+08:00',closesAt:b.closesAt+'+08:00'},u));if(b.action==='content')return Response.json(await saveContent(id,b.content,u.email));if(b.action==='review')return Response.json(await reviewCampaign(id,u.email,b.confirmed===true));if(b.action==='transition')return Response.json(await changeCampaign(id,b.status,u.email));if(b.action==='consolidate')return Response.json(await preparePo(id,u.email));if(b.action==='shipment')return Response.json(await advanceShipment(id,textValue(b.state,100),textValue(b.tracking||'',1000),textValue(b.reference||'',200),u.email));
 if(b.action==='authorization'){const brand=textValue(b.brand,100),url=textValue(b.documentUrl,2048);if(!brand||!approvedImage(url)||Date.parse(b.validUntil)<=Date.now()||!Number.isFinite(Date.parse(b.validUntil)))throw new CommerceError('Valid brand evidence and future expiration required',400);const rid=crypto.randomUUID();await database().batch([statement('INSERT INTO authorizations(id,brand,document_url,valid_until,created_by) VALUES(?,?,?,?,?)',rid,brand,url,new Date(b.validUntil).toISOString(),u.userId),audit(u.email,'AUTHORIZATION_RECORDED',rid,{brand,url})]);return Response.json({id:rid})}
 if(b.action==='approvePo'){if(b.confirmed!==true)throw new CommerceError('Human supplier approval required',400);const po=await one('SELECT * FROM commerce_purchase_orders WHERE id=?',id);if(!po||po.status!=='PREPARED')throw new CommerceError('PO is not awaiting approval');await database().batch([statement('UPDATE commerce_purchase_orders SET status=?,approved_by=?,approved_at=? WHERE id=? AND status=?','APPROVED',u.email,iso(),id,'PREPARED'),audit(u.email,'PO_APPROVED',id,{quantities:JSON.parse(po.quantities),bindingSubmission:false})]);return Response.json({approved:true})}
 if(b.action==='supplierRecord'){const po=await one('SELECT * FROM commerce_purchase_orders WHERE id=?',id),ref=textValue(b.reference,200),url=textValue(b.invoiceUrl,2048);if(!po||po.status!=='APPROVED'||!ref||!approvedImage(url))throw new CommerceError('Approved PO, actual supplier reference and HTTPS invoice required');await database().batch([statement('UPDATE commerce_purchase_orders SET status=?,supplier_reference=?,invoice_url=? WHERE id=? AND status=?','SUBMITTED',ref,url,id,'APPROVED'),audit(u.email,'SUPPLIER_ORDER_RECORDED',id,{reference:ref,invoiceUrl:url})]);return Response.json({recorded:true})}
 if(b.action==='supportReply'){const ticket=await one('SELECT * FROM commerce_tickets WHERE id=?',id),response=textValue(b.response);if(!ticket||!response)throw new CommerceError('Ticket and response required',400);await database().batch([statement('UPDATE commerce_tickets SET response=?,status=? WHERE id=?',response,'ANSWERED',id),mailJob(ticket.email,'BEAUTY DROP support / Тусламж',response),audit(u.email,'SUPPORT_REPLIED',id,{})]);return Response.json({saved:true})}
 if(b.action==='recordRefund'){const order=await one('SELECT o.*,m.email,m.shipping_state FROM orders o JOIN commerce_order_meta m ON m.order_id=o.id WHERE o.id=?',id),reference=textValue(b.reference,200),evidence=textValue(b.evidenceUrl,2048);if(!order||!['REFUND_REQUIRED','PAID'].includes(order.status)||order.shipping_state!=='PRE_ORDER'||!reference||!approvedImage(evidence)||b.confirmed!==true)throw new CommerceError('An actual reconciled refund, proof URL and explicit staff confirmation are required');const eligibility="SELECT o.id FROM orders o WHERE o.id=? AND o.status IN ('REFUND_REQUIRED','PAID') AND NOT EXISTS(SELECT 1 FROM commerce_purchase_orders p WHERE p.campaign_id=o.campaign_id)";const statements=[statement('INSERT INTO commerce_events(id,order_id,state,note,created_at) VALUES(?,('+eligibility+'),?,?,?)',crypto.randomUUID(),id,'REFUNDED_MANUAL','Staff reconciled external refund: '+reference,iso()),statement('UPDATE orders SET status=? WHERE id=?','REFUNDED_MANUAL',id),audit(u.email,'REFUND_RECONCILED',id,{reference,evidenceUrl:evidence,amountMnt:order.total_mnt,externalTransferConfirmed:true})];if(order.status==='PAID'){const lines=await (await import('@/lib/commerce-store')).rows('SELECT l.quantity,lv.variant_id FROM order_lines l JOIN commerce_line_variants lv ON lv.line_id=l.id WHERE l.order_id=?',id);for(const l of lines)statements.push(statement('UPDATE commerce_variants SET paid_qty=paid_qty-? WHERE id=?',l.quantity,l.variant_id),statement('UPDATE commerce_usage SET quantity=quantity-? WHERE user_id=? AND variant_id=?',l.quantity,order.user_id,l.variant_id))}statements.push(mailJob(order.email,'Refund recorded / Буцаалт бүртгэгдлээ',id+'\n'+reference));await database().batch(statements);return Response.json({recorded:true,automaticProviderRefund:false})}
 if(b.action==='reviewImport'){const item=await one('SELECT * FROM commerce_imports WHERE id=?',id);if(!item||item.status!=='REVIEW'||b.confirmed!==true)throw new CommerceError('Pending import and human review required');await database().batch([statement('UPDATE commerce_imports SET status=? WHERE id=? AND status=?',b.reject?'REJECTED':'REVIEWED',id,'REVIEW'),audit(u.email,'IMPORT_REVIEWED',id,{rejected:!!b.reject,publication:false})]);return Response.json({reviewed:true})}
 if(b.action==='import'){const payload=textValue(b.payload,200000),partner=textValue(b.partner,100);if(!partner||!['JSON','CSV','XML','EMAIL'].includes(b.format))throw new CommerceError('Partner and supported format required',400);if(b.format==='JSON'){try{JSON.parse(payload)}catch{throw new CommerceError('Malformed JSON',400)}}const rid=crypto.randomUUID();await database().batch([statement('INSERT INTO commerce_imports(id,partner_id,format,payload,status,created_by,created_at) VALUES(?,?,?,?,?,?,?)',rid,partner,b.format,payload,'REVIEW',u.email,iso()),audit(u.email,'PARTNER_IMPORT_STAGED',rid,{format:b.format,publication:false})]);return Response.json({id:rid})}
 throw new CommerceError('Unsupported action',400)
 }catch(e){return failure(e)}}
