import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database,isAdmin,validOrigin} from '@/db/raw';
import {transition,CampaignStatus} from '@/lib/catalog';
async function admin(){const u=await getChatGPTUser();return u&&isAdmin(u.email)?u:null;}
export async function GET(){const u=await admin();if(!u)return Response.json({error:'Administrative access required'},{status:403});try{const db=database();const [campaigns,audit,authorizations,consolidation]=await Promise.all([db.prepare('SELECT * FROM campaigns ORDER BY created_at DESC LIMIT 100').all(),db.prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 100').all(),db.prepare('SELECT * FROM authorizations LIMIT 100').all(),db.prepare("SELECT l.sku,l.variant,SUM(l.quantity) as quantity FROM order_lines l JOIN orders o ON o.id=l.order_id WHERE o.status='PAID' GROUP BY l.sku,l.variant").all()]);return Response.json({campaigns:campaigns.results,audit:audit.results,authorizations:authorizations.results,consolidation:consolidation.results});}catch(e){console.error('admin load failed',e);return Response.json({error:'Administration storage unavailable'},{status:503})}}
export async function POST(req:Request){if(!validOrigin(req))return Response.json({error:'Invalid origin'},{status:403});const u=await admin();if(!u)return Response.json({error:'Administrative access required'},{status:403});try{const b=await req.json() as any;const db=database();const now=new Date().toISOString();let id=crypto.randomUUID();let statement:ReturnType<ReturnType<typeof database>['prepare']>;
if(b.action==='create'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>120||typeof b.brand!=='string'||!b.brand.trim()||b.brand.length>80)return Response.json({error:'A campaign name and brand are required'},{status:400});const opens=new Date(b.opensAt+'+08:00'),closes=new Date(b.closesAt+'+08:00');if(!Number.isFinite(opens.getTime())||!Number.isFinite(closes.getTime())||closes<=opens)return Response.json({error:'Closing time must be after opening time (UTC +08:00)'},{status:400});statement=db.prepare('INSERT INTO campaigns(id,name,brand,status,opens_at,closes_at,created_by,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,b.name.trim(),b.brand.trim(),'DRAFT',opens.toISOString(),closes.toISOString(),u.userId,now);}
else if(b.action==='authorization'){if(typeof b.brand!=='string'||b.brand.length>80||!b.brand.trim()||typeof b.documentUrl!=='string'||!/^https:\/\//.test(b.documentUrl)||b.documentUrl.length>2048||!Number.isFinite(Date.parse(b.validUntil))||Date.parse(b.validUntil)<=Date.now())return Response.json({error:'A brand, HTTPS evidence URL and future expiry date are required'},{status:400});statement=db.prepare('INSERT INTO authorizations(id,brand,document_url,valid_until,created_by) VALUES(?,?,?,?,?)').bind(id,b.brand,b.documentUrl,b.validUntil,u.userId);}
else if(b.action==='transition'){id=b.id;const c=await db.prepare('SELECT * FROM campaigns WHERE id=?').bind(id).first<any>();if(!c||!transition[c.status as CampaignStatus]?.includes(b.status))return Response.json({error:'Invalid state transition. Closed campaigns can never reopen.'},{status:409});if(['UPCOMING','LIVE'].includes(b.status))return Response.json({error:'Publication requires reviewed brand evidence, approved products, allocations, pricing and policies. Publication is locked until the supplier review workflow is configured.'},{status:409});statement=db.prepare('UPDATE campaigns SET status=?,closed_at=? WHERE id=? AND status=?').bind(b.status,b.status==='CLOSED'?now:c.closed_at,id,c.status);}
else return Response.json({error:'Unsupported action'},{status:400});const log=db.prepare('INSERT INTO audit_logs(id,actor,action,record_id,detail,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.email,b.action,id,JSON.stringify({status:b.status??'DRAFT'}),now);await db.batch([statement,log]);return Response.json({id,saved:true});}catch(e){console.error('admin action failed',e);return Response.json({error:'Could not save this change'},{status:503})}}
